import { MSats } from './units'

export type RpcMethodNames = keyof RpcMethods
export type RpcPayload<M extends RpcMethodNames> = RpcMethods[M][0]
export type RpcResponse<M extends RpcMethodNames> = RpcMethods[M][1]

// used by generated code
declare const __opaque_type__: unique symbol // https://blog.beraliv.dev/2021-05-07-opaque-type-in-typescript
export type Opaque<BaseType, TagName> = BaseType & {
    readonly [__opaque_type__]: TagName
}

// this was auto generated by ts-bindgen.sh

export interface BalanceEvent {
    federationId: RpcFederationId
    balance: RpcAmount
}

export type ErrorCode =
    | 'initializationFailed'
    | 'badRequest'
    | 'invalidInvoice'
    | 'invalidMnemonic'
    | 'ecashCancelFailed'
    | 'socialRecoveryNotSupported'
    | 'nostrNotSupported'
    | 'panic'
    | 'notSupportedInVersion'
    | 'stabilityPoolNotSupported'

export type Event =
    | { transaction: TransactionEvent }
    | { log: LogEvent }
    | { federation: RpcFederation }
    | { balance: BalanceEvent }
    | { panic: PanicEvent }
    | { stabilityPoolDeposit: StabilityPoolDepositEvent }
    | { stabilityPoolWithdrawal: StabilityPoolWithdrawalEvent }

export interface LogEvent {
    log: string
}

export interface PanicEvent {
    message: string
}

export type RpcAmount = MSats

export interface RpcBalanceInfo {
    tiers: Record<string, number>
}

export interface RpcBitcoinDetails {
    address: string
    expiresAt: number
}

export interface RpcEcashInfo {
    amount: RpcAmount
    federationId: RpcFederationId | null
}

export interface RpcFederation {
    balance: RpcAmount
    id: RpcFederationId
    network: string
    name: string
    inviteCode: string
    meta: Record<string, string>
    socialRecoveryActive: boolean
    nodes: Record<string, { url: string; name: string }>
    version: number
    clientConfig: RpcJsonClientConfig | null
}

export type RpcFederationId = string

export interface RpcGenerateEcashResponse {
    ecash: string
    cancelAt: number
}

export interface RpcInvoice {
    paymentHash: string
    amount: RpcAmount
    fee: RpcAmount
    description: string
    invoice: string
}

export interface RpcJsonClientConfig {
    global: unknown
    modules: Record<string, unknown>
}

export interface RpcLightningDetails {
    invoice: string
    fee: RpcAmount | null
}

export type RpcLightningGateway = RpcLightningGatewayV0 | RpcLightningGatewayV1

export interface RpcLightningGatewayV0 {
    nodePubKey: RpcPublicKey
    mintPubKey: string
    api: string
    active: boolean
}

export interface RpcLightningGatewayV1 {
    nodePubKey: RpcPublicKey
    gatewayId: RpcPublicKey
    api: string
    active: boolean
}

export type RpcLnPayState =
    | { type: 'created' }
    | { type: 'canceled' }
    | { type: 'funded' }
    | { type: 'waitingForRefund'; block_height: number; gateway_error: string }
    | { type: 'awaitingChange' }
    | { type: 'success'; preimage: string }
    | { type: 'refunded'; gateway_error: string }
    | { type: 'failed' }

export type RpcLnReceiveState =
    | { type: 'created' }
    | { type: 'waitingForPayment'; invoice: string; timeout: string }
    | { type: 'canceled'; reason: string }
    | { type: 'funded' }
    | { type: 'awaitingFunds' }
    | { type: 'claimed' }

export type RpcLnState = RpcLnPayState | RpcLnReceiveState

export interface RpcLockedSeek {
    initialAmount: RpcAmount
    initialAmountCents: number
    withdrawnAmount: RpcAmount
    withdrawnAmountCents: number
    feesPaidSoFar: RpcAmount
    firstLockStartTime: number
}

export interface RpcMethods {
    joinFederation: [
        { inviteCode: string },
        {
            balance: RpcAmount
            id: RpcFederationId
            network: string
            name: string
            inviteCode: string
            meta: Record<string, string>
            socialRecoveryActive: boolean
            nodes: Record<string, { url: string; name: string }>
            version: number
            clientConfig: RpcJsonClientConfig | null
        },
    ]
    leaveFederation: [{ federationId: RpcFederationId }, null]
    listFederations: [
        {},
        Array<{
            balance: RpcAmount
            id: RpcFederationId
            network: string
            name: string
            inviteCode: string
            meta: Record<string, string>
            socialRecoveryActive: boolean
            nodes: Record<string, { url: string; name: string }>
            version: number
            clientConfig: RpcJsonClientConfig | null
        }>,
    ]
    generateInvoice: [
        {
            federationId: RpcFederationId
            amount: RpcAmount
            description: string
        },
        string,
    ]
    decodeInvoice: [
        { invoice: string },
        {
            paymentHash: string
            amount: RpcAmount
            fee: RpcAmount
            description: string
            invoice: string
        },
    ]
    payInvoice: [
        { federationId: RpcFederationId; invoice: string },
        { preimage: string },
    ]
    listGateways: [
        { federationId: RpcFederationId },
        Array<RpcLightningGatewayV0 | RpcLightningGatewayV1>,
    ]
    switchGateway: [
        { federationId: RpcFederationId; gatewayId: RpcPublicKey },
        null,
    ]
    generateAddress: [{ federationId: RpcFederationId }, string]
    payAddress: [
        { federationId: RpcFederationId; address: string; sats: bigint },
        { txid: string },
    ]
    balanceInfo: [
        { federationId: RpcFederationId },
        { tiers: Record<string, number> },
    ]
    generateEcash: [
        { federationId: RpcFederationId; amount: RpcAmount },
        { ecash: string; cancelAt: number },
    ]
    receiveEcash: [{ federationId: RpcFederationId; ecash: string }, MSats]
    validateEcash: [
        { ecash: string },
        { amount: RpcAmount; federationId: RpcFederationId | null },
    ]
    cancelEcash: [{ federationId: RpcFederationId; ecash: string }, null]
    listTransactions: [
        { federationId: RpcFederationId; startTime?: number; limit?: number },
        Array<{
            id: string
            createdAt: number
            amount: RpcAmount
            direction: RpcTransactionDirection
            notes: string
            onchainState: RpcOnchainState | null
            bitcoin: RpcBitcoinDetails | null
            lnState: RpcLnState | null
            lightning: RpcLightningDetails | null
            oobState: RpcOOBState | null
            onchainWithdrawalDetails: WithdrawalDetails | null
        }>,
    ]
    updateTransactionNotes: [
        { federationId: RpcFederationId; transactionId: string; notes: string },
        null,
    ]
    getMnemonic: [{ federationId: RpcFederationId }, Array<string>]
    recoverFromMnemonic: [
        { federationId: RpcFederationId; mnemonic: Array<string> },
        string | null,
    ]
    uploadBackupFile: [
        { federationId: RpcFederationId; videoFilePath: string },
        string,
    ]
    locateRecoveryFile: [{}, string]
    validateRecoveryFile: [
        { federationId: RpcFederationId; path: string },
        boolean,
    ]
    recoveryQr: [
        { federationId: RpcFederationId },
        { recoveryId: RpcRecoveryId },
    ]
    socialRecoveryApprovals: [
        { federationId: RpcFederationId },
        {
            federationId: RpcFederationId
            approvals: Array<SocialRecoveryApproval>
            remaining: number
        },
    ]
    completeSocialRecovery: [{ federationId: RpcFederationId }, string | null]
    socialRecoveryDownloadVerificationDoc: [
        { federationId: RpcFederationId; recoveryId: RpcRecoveryId },
        string | null,
    ]
    approveSocialRecoveryRequest: [
        {
            federationId: RpcFederationId
            recoveryId: RpcRecoveryId
            peerId: RpcPeerId
            password: string
        },
        null,
    ]
    signLnurlMessage: [
        { message: string; federationId: RpcFederationId },
        { signature: string; pubkey: RpcPublicKey },
    ]
    xmppCredentials: [
        { federationId: RpcFederationId },
        { password: string; keypairSeed: string; username: string | null },
    ]
    backupXmppUsername: [
        { federationId: RpcFederationId; username: string },
        null,
    ]
    getNostrPubKey: [{ federationId: RpcFederationId }, string]
    signNostrEvent: [
        { eventHash: string; federationId: RpcFederationId },
        string,
    ]
    stabilityPoolAccountInfo: [
        { federationId: RpcFederationId },
        {
            idleBalance: RpcAmount
            stagedSeeks: Array<RpcAmount>
            stagedCancellation: number | null
            lockedSeeks: Array<RpcLockedSeek>
        },
    ]
    stabilityPoolDepositToSeek: [
        { federationId: RpcFederationId; amount: RpcAmount },
        string,
    ]
    stabilityPoolWithdraw: [
        {
            federationId: RpcFederationId
            unlockedAmount: RpcAmount
            lockedBps: number
        },
        string,
    ]
}

export type RpcOOBSpendState =
    | { type: 'created' }
    | { type: 'userCanceledProcessing' }
    | { type: 'userCanceledSuccess' }
    | { type: 'userCanceledFailure' }
    | { type: 'refunded' }
    | { type: 'success' }

export type RpcOOBState = { type: 'spend' } & RpcOOBSpendState

export type RpcOnchainDepositState =
    | { type: 'waitingForTransaction' }
    | ({ type: 'waitingForConfirmation' } & RpcOnchainDepositTransactionData)
    | ({ type: 'confirmed' } & RpcOnchainDepositTransactionData)
    | ({ type: 'claimed' } & RpcOnchainDepositTransactionData)
    | { type: 'failed' }

export interface RpcOnchainDepositTransactionData {
    txid: string
}

export type RpcOnchainState = RpcOnchainDepositState | RpcOnchainWithdrawState

export type RpcOnchainWithdrawState =
    | { type: 'created' }
    | { type: 'succeeded' }
    | { type: 'failed' }

export type RpcOperationId = string

export interface RpcPayAddressResponse {
    txid: string
}

export interface RpcPayInvoiceResponse {
    preimage: string
}

export type RpcPeerId = number

export type RpcPublicKey = string

export type RpcRecoveryId = string

export interface RpcSignedLnurlMessage {
    signature: string
    pubkey: RpcPublicKey
}

export interface RpcStabilityPoolAccountInfo {
    idleBalance: RpcAmount
    stagedSeeks: Array<RpcAmount>
    stagedCancellation: number | null
    lockedSeeks: Array<RpcLockedSeek>
}

export interface RpcTransaction {
    id: string
    createdAt: number
    amount: RpcAmount
    direction: RpcTransactionDirection
    notes: string
    onchainState: RpcOnchainState | null
    bitcoin: RpcBitcoinDetails | null
    lnState: RpcLnState | null
    lightning: RpcLightningDetails | null
    oobState: RpcOOBState | null
    onchainWithdrawalDetails: WithdrawalDetails | null
}

export type RpcTransactionDirection = 'receive' | 'send'

export interface RpcXmppCredentials {
    password: string
    keypairSeed: string
    username: string | null
}

export interface SocialRecoveryApproval {
    guardianName: string
    approved: boolean
}

export interface SocialRecoveryEvent {
    federationId: RpcFederationId
    approvals: Array<SocialRecoveryApproval>
    remaining: number
}

export interface StabilityPoolDepositEvent {
    federationId: RpcFederationId
    operationId: RpcOperationId
    state: StabilityPoolDepositState
}

export type StabilityPoolDepositState =
    | 'initiated'
    | 'txAccepted'
    | { txRejected: string }
    | { primaryOutputError: string }
    | 'success'

export interface StabilityPoolWithdrawalEvent {
    federationId: RpcFederationId
    operationId: RpcOperationId
    state: StabilityPoolWithdrawalState
}

export type StabilityPoolWithdrawalState =
    | 'withdrawUnlockedInitiated'
    | { txRejected: string }
    | 'withdrawUnlockedAccepted'
    | { primaryOutputError: string }
    | 'success'
    | { cancellationSubmissionFailure: string }
    | 'cancellationInitiated'
    | 'cancellationAccepted'
    | { awaitCycleTurnoverError: string }
    | { withdrawIdleSubmissionFailure: string }
    | 'withdrawIdleInitiated'
    | 'withdrawIdleAccepted'

export interface TransactionEvent {
    federationId: RpcFederationId
    transaction: RpcTransaction
}

export interface WithdrawalDetails {
    txid: string
    fee: bigint
    feeRate: bigint
}
