[package]
name = "fedi-monitoring"
version = "0.1.0"
edition = "2021"

[dependencies]

fedimint-client = { workspace = true }
fedimint-core = { workspace = true }
fedimint-ln-client = { workspace = true }
fedimint-logging = { workspace = true }
fedimint-mint-client = { workspace = true }
fedimint-wallet-client = { workspace = true }
ln-gateway = { workspace = true }


anyhow = "1"
axum = "0.6.18"
bitcoin = "0.29.2"
chrono = { version = "0.4.24", features = ["serde"] }
clap = { version = "4.3.0", features = ["derive", "env"] }
futures = "0.3.16"
lightning-invoice = { version = "0.21.0", features = [ "serde" ] }
reqwest = { version = "0.11.18", features = ["json"] }
rpassword = "7.2.0"
serde = { version = "1.0.149", features = [ "derive" ] }
serde_with = "3.0.0"
tempfile = "3"
tokio = { version = "1", features = ["full"] }
tonic_lnd = { git = "https://github.com/fedimint/tonic_lnd", branch="lnd-client-features", features = ["lightningrpc", "routerrpc"] }
tracing = "0.1"
prometheus = "0.13.3"
