[workspace]
members = [
    "fedimintd",
    "fedimint-cli",
    "fedimint-client-fedi",
    "fedi-social-common",
    "fedi-social-server",
    "fedi-social-client",
]
resolver = "2"

[workspace.metadata]
authors = ["The Fedi Developers"]
edition = "2021"
description = "Fedi"
documentation = "https://github.com/fedibtc/fedimintd-fedi"
readme = "README.md"
homepage = "https://fedi.xyz"
repository = "https://github.com/fedibtc/fedimintd-fedi"
license-file = "LICENSE"
keywords = ["bitcoin", "lightning", "chaumian", "e-cash", "federated"]

[workspace.dependencies]
threshold_crypto = { git = "https://github.com/fedimint/threshold_crypto" }
stabilitypool-server = { git = "https://x-access-token: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@github.com/fedibtc/stabilitypool.git", rev = "bd379d49c1cd7a7686606fae780ae6e18bdeeb46" }
# stabilitypool-server = { path = "../stabilitypool/stabilitypool-server" }

# NOTE: You want to update the `fedimint` input git hash in `flake.nix` as well, to keep gateway-pkgs in sync
fedimintd = { git = "https://github.com/fedimint/fedimint", rev = "b283f4e2c5d4ccacd1293276e4880a5918013981" }
fedimint-cli = { git = "https://github.com/fedimint/fedimint", rev = "b283f4e2c5d4ccacd1293276e4880a5918013981" }
fedimint-build = { git = "https://github.com/fedimint/fedimint", rev = "b283f4e2c5d4ccacd1293276e4880a5918013981" }
fedimint-core = { git = "https://github.com/fedimint/fedimint", rev = "b283f4e2c5d4ccacd1293276e4880a5918013981" }
fedimint-server = { git = "https://github.com/fedimint/fedimint", rev = "b283f4e2c5d4ccacd1293276e4880a5918013981" }
fedimint-client = { git = "https://github.com/fedimint/fedimint", rev = "b283f4e2c5d4ccacd1293276e4880a5918013981" }
fedimint-derive-secret = { git = "https://github.com/fedimint/fedimint", rev = "b283f4e2c5d4ccacd1293276e4880a5918013981" }
fedimint-mint-client = { git = "https://github.com/fedimint/fedimint", rev = "b283f4e2c5d4ccacd1293276e4880a5918013981" }
fedimint-wallet-client = { git = "https://github.com/fedimint/fedimint", rev = "b283f4e2c5d4ccacd1293276e4880a5918013981" }
fedimint-ln-client = { git = "https://github.com/fedimint/fedimint", rev = "b283f4e2c5d4ccacd1293276e4880a5918013981" }
mint-client = { git = "https://github.com/fedimint/fedimint", rev = "b283f4e2c5d4ccacd1293276e4880a5918013981" }
fedimint-aead = { git = "https://github.com/fedimint/fedimint", rev = "b283f4e2c5d4ccacd1293276e4880a5918013981" }
tbs = { git = "https://github.com/fedimint/fedimint", rev = "b283f4e2c5d4ccacd1293276e4880a5918013981" }

# commented-out local deps for easy debugging
# fedimintd = { path = "../fedimint/fedimintd" }
# fedimint-build = { path = "../fedimint/fedimint-build" }
# fedimint-core = { path = "../fedimint/fedimint-core" }
# fedimint-server = { path = "../fedimint/fedimint-server" }
# fedimint-client = { path = "../fedimint/fedimint-client" }
# fedimint-derive-secret = { path = "../fedimint/crypto/derive-secret" }
# fedimint-mint-client = { path = "../fedimint/modules/fedimint-mint-client" }
# fedimint-wallet-client = { path = "../fedimint/modules/fedimint-wallet-client" }
# fedimint-ln-client = { path = "../fedimint/modules/fedimint-ln-client" }
# mint-client = { path = "../fedimint/client/client-lib" }
# fedimint-aead = { path = "../fedimint/crypto/aead" }
# tbs = { path = "../fedimint/crypto/tbs" }

[profile.dev]
split-debuginfo = "packed"

# in dev mode optimize crates that are perf-critical (usually just crypto crates)
[profile.dev.package]
secp256k1 = { opt-level = 3 }
secp256k1-zkp = { opt-level = 3 }
secp256k1-sys = { opt-level = 3 }
secp256k1-zkp-sys = { opt-level = 3 }
bitcoin_hashes = { opt-level = 3 }
ff = { opt-level = 3 }
group = { opt-level = 3 }
pairing = { opt-level = 3 }
rand_core = { opt-level = 3 }
byteorder = { opt-level = 3 }
zeroize = { opt-level = 3 }
bls12_381 = { opt-level = 3 }
subtle = { opt-level = 3 }
ring = { opt-level = 3 }
threshold_crypto = { opt-level = 3 }


[patch.crates-io]
secp256k1-zkp = { git = "https://github.com/dpc/rust-secp256k1-zkp/", branch = "sanket-pr" }

