cargo-features = ["trim-paths"]

[workspace]
members = [
    "devops-cli",
    "fedimintd",
    "fedimint-cli",
    "fedi-social-common",
    "fedi-social-server",
    "fedi-social-client",
    "bridge/fedi-ffi",
    "bridge/ffi-bindgen",
    "bridge/fedi-wasm",
    "bridge/fedi-rpc-server",
    "bridge/v0-rocksdb",
    "stability-pool/stability-pool-client",
    "stability-pool/stability-pool-common",
    "stability-pool/stability-pool-server",
    "stability-pool/stability-pool-tests",
]
default-members = [
    "devops-cli",
    "fedimintd",
    "fedimint-cli",
    "fedi-social-common",
    "fedi-social-server",
    "fedi-social-client",
    "bridge/fedi-ffi",
    "bridge/ffi-bindgen",
    "stability-pool/stability-pool-client",
    "stability-pool/stability-pool-common",
    "stability-pool/stability-pool-server",
    "stability-pool/stability-pool-tests",
]
resolver = "2"

[profile.release]
trim-paths = "all"
lto = "fat"
codegen-units = 1
# we need debug symbols for debugging panics and such, at least on the backend
# if don't need them *somewhere*, we should manually call `strip` after the binary
# is built
debug = "line-tables-only"
strip = false

[workspace.metadata]
authors = ["The Fedi Developers"]
edition = "2021"
description = "Fedi"
documentation = "https://github.com/fedibtc/fedimintd-fedi"
readme = "README.md"
homepage = "https://fedi.xyz"
repository = "https://github.com/fedibtc/fedimintd-fedi"
license-file = "LICENSE"
keywords = ["bitcoin", "lightning", "chaumian", "e-cash", "federated"]

[workspace.dependencies]
fedimint_threshold_crypto = { version = "0.1", package = "fedimint-threshold-crypto" }
threshold_crypto = { git = "https://github.com/fedimint/threshold_crypto", rev = "9b0eeec8f23f41a385174c0d84290cbf8d88a656" }

fedimintd = { git = "https://x-access-token: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@github.com/fedibtc/fedimint-fedi", tag = "v0.2.1-rc4" }
fedimint-cli = { git = "https://x-access-token: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@github.com/fedibtc/fedimint-fedi", tag = "v0.2.1-rc4" }
fedimint-build = { git = "https://x-access-token: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@github.com/fedibtc/fedimint-fedi", tag = "v0.2.1-rc4" }
fedimint-core = { git = "https://x-access-token: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@github.com/fedibtc/fedimint-fedi", tag = "v0.2.1-rc4" }
fedimint-server = { git = "https://x-access-token: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@github.com/fedibtc/fedimint-fedi", tag = "v0.2.1-rc4" }
fedimint-client = { git = "https://x-access-token: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@github.com/fedibtc/fedimint-fedi", tag = "v0.2.1-rc4" }
fedimint-derive-secret = { git = "https://x-access-token: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@github.com/fedibtc/fedimint-fedi", tag = "v0.2.1-rc4" }
fedimint-mint-client = { git = "https://x-access-token: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@github.com/fedibtc/fedimint-fedi", tag = "v0.2.1-rc4" }
fedimint-wallet-client = { git = "https://x-access-token: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@github.com/fedibtc/fedimint-fedi", tag = "v0.2.1-rc4" }
fedimint-ln-client = { git = "https://x-access-token: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@github.com/fedibtc/fedimint-fedi", tag = "v0.2.1-rc4" }
fedimint-ln-common = { git = "https://x-access-token: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@github.com/fedibtc/fedimint-fedi", tag = "v0.2.1-rc4" }
fedimint-client-legacy = { git = "https://x-access-token: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@github.com/fedibtc/fedimint-fedi", tag = "v0.2.1-rc4" }
fedimint-aead = { git = "https://x-access-token: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@github.com/fedibtc/fedimint-fedi", tag = "v0.2.1-rc4" }
fedimint-rocksdb = { git = "https://x-access-token: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@github.com/fedibtc/fedimint-fedi", tag = "v0.2.1-rc4" }
fedimint-bip39 = { git = "https://x-access-token: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@github.com/fedibtc/fedimint-fedi", tag = "v0.2.1-rc4" }
fedimint-logging = { git = "https://x-access-token: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@github.com/fedibtc/fedimint-fedi", tag = "v0.2.1-rc4" }
devimint = { git = "https://x-access-token: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@github.com/fedibtc/fedimint-fedi", tag = "v0.2.1-rc4" }
ln-gateway = { git = "https://x-access-token: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@github.com/fedibtc/fedimint-fedi", tag = "v0.2.1-rc4" }

# Uncomment these to use local fedimint v2
# fedimintd = { path = "../fedimint/fedimintd" }
# fedimint-cli = { path = "../fedimint/fedimint-cli" }
# fedimint-build = { path = "../fedimint/fedimint-build" }
# fedimint-core = { path = "../fedimint/fedimint-core" }
# fedimint-server = { path = "../fedimint/fedimint-server" }
# fedimint-client = { path = "../fedimint/fedimint-client" }
# fedimint-derive-secret = { path = "../fedimint/crypto/derive-secret" }
# fedimint-mint-client = { path = "../fedimint/modules/fedimint-mint-client" }
# fedimint-wallet-client = { path = "../fedimint/modules/fedimint-wallet-client" }
# fedimint-ln-client = { path = "../fedimint/modules/fedimint-ln-client" }
# fedimint-ln-common = { path = "../fedimint/modules/fedimint-ln-common" }
# fedimint-client-legacy = { path = "../fedimint/fedimint-client-legacy" }
# fedimint-aead = { path = "../fedimint/crypto/aead" }
# fedimint-rocksdb = { path = "../fedimint/fedimint-rocksdb" }
# fedimint-bip39 = { path = "../fedimint/fedimint-bip39" }
# fedimint-logging = { path = "../fedimint/fedimint-logging" }
# devimint = { path = "../fedimint/devimint" }
# ln-gateway = { path = "../fedimint/gateway/ln-gateway" }

# NOTE: You want to update the `fedimint` input git hash in `flake.nix` as well, to keep gateway-pkgs in sync
# NOTE: To use local fedimint depenencies, comment out the "paths" section in .cargo/config.toml
fedimintd-v1 = { package = "fedimintd", git = "https://github.com/fedimint/fedimint", branch = "releases/v0.1" }
fedimint-cli-v1 = { package = "fedimint-cli", git = "https://github.com/fedimint/fedimint", branch = "releases/v0.1" }
fedimint-build-v1 = { package = "fedimint-build", git = "https://github.com/fedimint/fedimint", branch = "releases/v0.1" }
fedimint-core-v1 = { package = "fedimint-core", git = "https://github.com/fedimint/fedimint", branch = "releases/v0.1" }
fedimint-server-v1 = { package = "fedimint-server", git = "https://github.com/fedimint/fedimint", branch = "releases/v0.1" }
fedimint-client-v1 = { package = "fedimint-client", git = "https://github.com/fedimint/fedimint", branch = "releases/v0.1" }
fedimint-derive-secret-v1 = { package = "fedimint-derive-secret", git = "https://github.com/fedimint/fedimint", branch = "releases/v0.1" }
fedimint-mint-client-v1 = { package = "fedimint-mint-client", git = "https://github.com/fedimint/fedimint", branch = "releases/v0.1" }
fedimint-wallet-client-v1 = { package = "fedimint-wallet-client", git = "https://github.com/fedimint/fedimint", branch = "releases/v0.1" }
fedimint-ln-client-v1 = { package = "fedimint-ln-client", git = "https://github.com/fedimint/fedimint", branch = "releases/v0.1" }
fedimint-client-legacy-v1 = { package = "fedimint-client-legacy", git = "https://github.com/fedimint/fedimint", branch = "releases/v0.1" }
fedimint-aead-v1 = { package = "fedimint-aead", git = "https://github.com/fedimint/fedimint", branch = "releases/v0.1" }
fedimint-rocksdb-v1 = { package = "fedimint-rocksdb", git = "https://github.com/fedimint/fedimint", branch = "releases/v0.1" }
fedimint-bip39-v1 = { package = "fedimint-bip39", git = "https://github.com/fedimint/fedimint", branch = "releases/v0.1" }
tbs-v1 = { package = "tbs", git = "https://github.com/fedimint/fedimint", branch = "releases/v0.1" }
fedimint-logging-v1 = { package = "fedimint-logging", git = "https://github.com/fedimint/fedimint", branch = "releases/v0.1" }
devimint-v1 = { package = "devimint", git = "https://github.com/fedimint/fedimint", branch = "releases/v0.1" }
ln-gateway-v1 = { package = "ln-gateway", git = "https://github.com/fedimint/fedimint", branch = "releases/v0.1" }
fedi-social-client-v1 = { package = "fedi-social-client", git = "https://x-access-token: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@github.com/fedibtc/fedi", branch = "pre-0.2" }
stability-pool-client-v1 = { package = "stability-pool-client", git = "https://x-access-token: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@github.com/fedibtc/fedi", branch = "pre-0.2" }

# Uncomment these to use local fedimint v1
# fedimintd-v1 = { path = "../fedimint/fedimintd"}
# fedimint-cli-v1 = { path = "../fedimint/fedimint-cli"}
# fedimint-build-v1 = { path = "../fedimint/fedimint-build"}
# fedimint-core-v1 = { path = "../fedimint/fedimint-core"}
# fedimint-server-v1 = { path = "../fedimint/fedimint-server"}
# fedimint-client-v1 = { path = "../fedimint/fedimint-client"}
# fedimint-derive-secret-v1 = { path = "../fedimint/crypto/derive-secret"}
# fedimint-mint-client-v1 = { path = "../fedimint/modules/fedimint-mint-client"}
# fedimint-wallet-client-v1 = { path = "../fedimint/modules/fedimint-wallet-client"}
# fedimint-ln-client-v1 = { path = "../fedimint/modules/fedimint-ln-client"}
# fedimint-client-legacy-v1 = { path = "../fedimint/fedimint-client-legacy"}
# fedimint-aead-v1 = { path = "../fedimint/crypto/aead"}
# fedimint-rocksdb-v1 = { path = "../fedimint/fedimint-rocksdb"}
# fedimint-bip39-v1 = { path = "../fedimint/fedimint-bip39"}
# tbs-v1 = { path = "../fedimint/crypto/tbs"}
# fedimint-logging-v1 = { path = "../fedimint/fedimint-logging"}
# devimint-v1 = { path = "../fedimint/devimint"}
# ln-gateway-v1 = { path = "../fedimint/gateway/ln-gateway"}
# stability-pool-client-v1 = { path = "../fedi/stability-pool/stability-pool-client" }

fedimint-rocksdb-v0 = { package = "fedimint-rocksdb", git = "https://x-access-token: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@github.com/fedibtc/fedimint-fedi", branch = "ma/rel-a05-backport" }
fedimint-core-v0 = { package = "fedimint-core", git = "https://x-access-token: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@github.com/fedibtc/fedimint-fedi", branch = "ma/rel-a05-backport" }
fedimint-client-v0 = { package = "fedimint-client", git = "https://x-access-token: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@github.com/fedibtc/fedimint-fedi", branch = "ma/rel-a05-backport" }
fedimint-ln-client-v0 = { package = "fedimint-ln-client", git = "https://x-access-token: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@github.com/fedibtc/fedimint-fedi", branch = "ma/rel-a05-backport" }
fedimint-mint-client-v0 = { package = "fedimint-mint-client", git = "https://x-access-token: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@github.com/fedibtc/fedimint-fedi", branch = "ma/rel-a05-backport" }
fedimint-wallet-client-v0 = { package = "fedimint-wallet-client", git = "https://x-access-token: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@github.com/fedibtc/fedimint-fedi", branch = "ma/rel-a05-backport" }
fedimint-derive-secret-v0 = { package = "fedimint-derive-secret", git = "https://x-access-token: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@github.com/fedibtc/fedimint-fedi", branch = "ma/rel-a05-backport" }
fedimint-logging-v0 = { package = "fedimint-logging", git = "https://x-access-token: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@github.com/fedibtc/fedimint-fedi", branch = "ma/rel-a05-backport" }
fedimint-aead-v0 = { package = "fedimint-aead", git = "https://x-access-token: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@github.com/fedibtc/fedimint-fedi", branch = "ma/rel-a05-backport" }
fedimint-bip39-v0 = { package = "fedimint-bip39", git = "https://x-access-token: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@github.com/fedibtc/fedimint-fedi", branch = "ma/rel-a05-backport" }

# Uncomment these to use local fedimint v0
# (you need to also do this for bridge/v0-rocksdb crate)
# fedimint-rocksdb-v0 = { package = "fedimint-rocksdb", path = "../fedimint/fedimint-rocksdb" }
# fedimint-core-v0 = { package = "fedimint-core", path = "../fedimint/fedimint-core" }
# fedimint-client-v0 = { package = "fedimint-client", path = "../fedimint/fedimint-client" }
# fedimint-ln-client-v0 = { package = "fedimint-ln-client", path = "../fedimint/modules/fedimint-ln-client" }
# fedimint-mint-client-v0 = { package = "fedimint-mint-client", path = "../fedimint/modules/fedimint-mint-client" }
# fedimint-wallet-client-v0 = { package = "fedimint-wallet-client", path = "../fedimint/modules/fedimint-wallet-client" }
# fedimint-derive-secret-v0 = { package = "fedimint-derive-secret", path = "../fedimint/crypto/derive-secret" }
# fedimint-logging-v0 = { package = "fedimint-logging", path = "../fedimint/fedimint-logging" }
# fedimint-aead-v0 = { package = "fedimint-aead", path = "../fedimint/crypto/aead" }
# fedimint-bip39-v0 = { package = "fedimint-bip39", path = "../fedimint/fedimint-bip39" }

uniffi_bindgen = "0.21.1"

[profile.dev]
debug = "line-tables-only"
trim-paths = "object"

# in dev mode optimize crates that are perf-critical (usually just crypto crates)
[profile.dev.package]
secp256k1 = { opt-level = 3 }
secp256k1-zkp = { opt-level = 3 }
secp256k1-sys = { opt-level = 3 }
secp256k1-zkp-sys = { opt-level = 3 }
bitcoin_hashes = { opt-level = 3 }
ff = { opt-level = 3 }
group = { opt-level = 3 }
pairing = { opt-level = 3 }
rand_core = { opt-level = 3 }
byteorder = { opt-level = 3 }
zeroize = { opt-level = 3 }
bls12_381 = { opt-level = 3 }
subtle = { opt-level = 3 }
ring = { opt-level = 3 }
threshold_crypto = { opt-level = 3 }

# ios gets its own profile since it crashes on opt-level 0
[profile.dev-ios]
inherits = "dev"
opt-level = 1

[profile.ci]
inherits = "dev"
debug = "line-tables-only"
incremental = false

# Workaround: https://github.com/rust-lang/cargo/issues/12457 which causes
#             https://github.com/ipetkov/crane/issues/370
[profile.dev.build-override]
debug = false
[profile.ci.build-override]
debug = false
[profile.release.build-override]
debug = false

[patch.crates-io]
secp256k1-zkp = { git = "https://github.com/dpc/rust-secp256k1-zkp/", branch = "sanket-pr" }
uniffi_bindgen = { git = "https://github.com/fedibtc/uniffi-rs", rev = "d00f5ef23553665e2175ae98c12b005d46b26f7a" }
ring = { git = "https://github.com/dpc/ring", rev = "5493e7e76d0d8fb1d3cbb0be9c4944700741b802" }
