[workspace]
members = [
    "fedimintd",
    "fedimint-cli",
    "fedimint-client-fedi",
    "fedi-social-common",
    "fedi-social-server",
    "fedi-social-client",
    "bridge/fedi-ffi",
    "bridge/ffi-bindgen",
    "bridge/fedi-wasm",
]
default-members = [
    "fedimintd",
    "fedimint-cli",
    "fedimint-client-fedi",
    "fedi-social-common",
    "fedi-social-server",
    "fedi-social-client",
    "bridge/fedi-ffi",
    "bridge/ffi-bindgen",
]
resolver = "2"

[profile.release-smaller]
inherits = "release"
opt-level = 'z'      # Optimize for size.
lto = true           # Enable Link Time Optimization
codegen-units = 1    # Reduce number of codegen units to increase optimizations.
panic = 'abort'      # Abort on panic
strip = true         # Strip symbols from binary*

[workspace.metadata]
authors = ["The Fedi Developers"]
edition = "2021"
description = "Fedi"
documentation = "https://github.com/fedibtc/fedimintd-fedi"
readme = "README.md"
homepage = "https://fedi.xyz"
repository = "https://github.com/fedibtc/fedimintd-fedi"
license-file = "LICENSE"
keywords = ["bitcoin", "lightning", "chaumian", "e-cash", "federated"]

[workspace.dependencies]
threshold_crypto = { git = "https://github.com/fedimint/threshold_crypto" }


# stabilitypool-server = { git = "https://x-access-token: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@github.com/fedibtc/stabilitypool", rev = "e8d07c283ac8af081ecb6fcfd8fc193c503da5ff" }
# stabilitypool-client = { git = "https://x-access-token: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@github.com/fedibtc/stabilitypool", rev = "e8d07c283ac8af081ecb6fcfd8fc193c503da5ff" }
# stabilitypool-server = { path = "../stabilitypool/stabilitypool-server" }
# stabilitypool-client = { path = "../stabilitypool/stabilitypool-client"}


# NOTE: You want to update the `fedimint` input git hash in `flake.nix` as well, to keep gateway-pkgs in sync
# NOTE: To use local fedimint depenencies, comment out the "paths" section in .cargo/config.toml
fedimintd = { git = "https://github.com/fedimint/fedimint" }
fedimint-cli = { git = "https://github.com/fedimint/fedimint" }
fedimint-build = { git = "https://github.com/fedimint/fedimint" }
fedimint-core = { git = "https://github.com/fedimint/fedimint" }
fedimint-server = { git = "https://github.com/fedimint/fedimint" }
fedimint-client = { git = "https://github.com/fedimint/fedimint" }
fedimint-derive-secret = { git = "https://github.com/fedimint/fedimint" }
fedimint-mint-client = { git = "https://github.com/fedimint/fedimint" }
fedimint-wallet-client = { git = "https://github.com/fedimint/fedimint" }
fedimint-ln-client = { git = "https://github.com/fedimint/fedimint" }
fedimint-client-legacy = { git = "https://github.com/fedimint/fedimint" }
fedimint-aead = { git = "https://github.com/fedimint/fedimint" }
fedimint-rocksdb = { git = "https://github.com/fedimint/fedimint" }
tbs = { git = "https://github.com/fedimint/fedimint" }
fedimint-logging = { git = "https://github.com/fedimint/fedimint" }
fedimint-bin-tests = { git = "https://github.com/fedimint/fedimint" }
gateway-cli = { git = "https://github.com/fedimint/fedimint" }
ln-gateway = { git = "https://github.com/fedimint/fedimint" }

uniffi_bindgen = "0.21.1"

[profile.dev]
split-debuginfo = "packed"

# in dev mode optimize crates that are perf-critical (usually just crypto crates)
[profile.dev.package]
secp256k1 = { opt-level = 3 }
secp256k1-zkp = { opt-level = 3 }
secp256k1-sys = { opt-level = 3 }
secp256k1-zkp-sys = { opt-level = 3 }
bitcoin_hashes = { opt-level = 3 }
ff = { opt-level = 3 }
group = { opt-level = 3 }
pairing = { opt-level = 3 }
rand_core = { opt-level = 3 }
byteorder = { opt-level = 3 }
zeroize = { opt-level = 3 }
bls12_381 = { opt-level = 3 }
subtle = { opt-level = 3 }
ring = { opt-level = 3 }
threshold_crypto = { opt-level = 3 }

[patch.'https://github.com/fedimint/fedimint']
# fedimintd = { git = "https://x-access-token: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@github.com/fedibtc/fedimint-fedi", rev = "7ff6f95609e02fdaa9a0c272f8f8c92130b55890" }
# fedimint-cli = { git = "https://x-access-token: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@github.com/fedibtc/fedimint-fedi", rev = "7ff6f95609e02fdaa9a0c272f8f8c92130b55890" }
# fedimint-build = { git = "https://x-access-token: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@github.com/fedibtc/fedimint-fedi", rev = "7ff6f95609e02fdaa9a0c272f8f8c92130b55890" }
# fedimint-core = { git = "https://x-access-token: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@github.com/fedibtc/fedimint-fedi", rev = "7ff6f95609e02fdaa9a0c272f8f8c92130b55890" }
# fedimint-server = { git = "https://x-access-token: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@github.com/fedibtc/fedimint-fedi", rev = "7ff6f95609e02fdaa9a0c272f8f8c92130b55890" }
# fedimint-client = { git = "https://x-access-token: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@github.com/fedibtc/fedimint-fedi", rev = "7ff6f95609e02fdaa9a0c272f8f8c92130b55890" }
# fedimint-derive-secret = { git = "https://x-access-token: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@github.com/fedibtc/fedimint-fedi", rev = "7ff6f95609e02fdaa9a0c272f8f8c92130b55890" }
# fedimint-mint-client = { git = "https://x-access-token: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@github.com/fedibtc/fedimint-fedi", rev = "7ff6f95609e02fdaa9a0c272f8f8c92130b55890" }
# fedimint-wallet-client = { git = "https://x-access-token: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@github.com/fedibtc/fedimint-fedi", rev = "7ff6f95609e02fdaa9a0c272f8f8c92130b55890" }
# fedimint-ln-client = { git = "https://x-access-token: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@github.com/fedibtc/fedimint-fedi", rev = "7ff6f95609e02fdaa9a0c272f8f8c92130b55890" }
# fedimint-client-legacy = { git = "https://x-access-token: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@github.com/fedibtc/fedimint-fedi", rev = "7ff6f95609e02fdaa9a0c272f8f8c92130b55890" }
# fedimint-aead = { git = "https://x-access-token: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@github.com/fedibtc/fedimint-fedi", rev = "7ff6f95609e02fdaa9a0c272f8f8c92130b55890" }
# fedimint-rocksdb = { git = "https://x-access-token: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@github.com/fedibtc/fedimint-fedi", rev = "7ff6f95609e02fdaa9a0c272f8f8c92130b55890" }
# tbs = { git = "https://x-access-token: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@github.com/fedibtc/fedimint-fedi", rev = "7ff6f95609e02fdaa9a0c272f8f8c92130b55890" }
# fedimint-logging = { git = "https://x-access-token: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@github.com/fedibtc/fedimint-fedi", rev = "7ff6f95609e02fdaa9a0c272f8f8c92130b55890" }
# fedimint-bin-tests = { git = "https://x-access-token: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@github.com/fedibtc/fedimint-fedi", rev = "7ff6f95609e02fdaa9a0c272f8f8c92130b55890" }
fedimintd = { path = "../fedimint/fedimintd"}
fedimint-cli = { path = "../fedimint/fedimint-cli"}
fedimint-build = { path = "../fedimint/fedimint-build"}
fedimint-core = { path = "../fedimint/fedimint-core"}
fedimint-server = { path = "../fedimint/fedimint-server"}
fedimint-client = { path = "../fedimint/fedimint-client"}
fedimint-derive-secret = { path = "../fedimint/crypto/derive-secret"}
fedimint-mint-client = { path = "../fedimint/modules/fedimint-mint-client"}
fedimint-wallet-client = { path = "../fedimint/modules/fedimint-wallet-client"}
fedimint-ln-client = { path = "../fedimint/modules/fedimint-ln-client"}
fedimint-client-legacy = { path = "../fedimint/fedimint-client-legacy"}
fedimint-aead = { path = "../fedimint/crypto/aead"}
fedimint-rocksdb = { path = "../fedimint/fedimint-rocksdb"}
tbs = { path = "../fedimint/crypto/tbs"}
fedimint-logging = { path = "../fedimint/fedimint-logging"}
fedimint-bin-tests = { path = "../fedimint/fedimint-bin-tests"}
ln-gateway = { path = "../fedimint/gateway/ln-gateway"}
gateway-cli = { path = "../fedimint/gateway/cli"}

[patch.crates-io]
secp256k1-zkp = { git = "https://github.com/dpc/rust-secp256k1-zkp/", branch = "sanket-pr" }
uniffi_bindgen = { git = "https://github.com/fedibtc/uniffi-rs", rev = "a5fbebb8c733c6d450a803f6d2f6c760ce1d2d31" }
# ring: we overwrite via `cargo` wrapper and nix build, conditionally for wasm32 builds only
# FIXME: remove this once fedimint is upgraded to include 0.21.0
rocksdb = { git = "https://github.com/fedibtc/rust-rocksdb.git", rev = "c26cdef16eac3bae6925303e2f7d305d8ed2a72c" }
