# THIS FILE IS AUTOGENERATED FROM FLAKEBOX CONFIGURATION
alias b := build
alias c := check
alias t := test


[private]
default:
  @just --list


# run `cargo build` on everything
build:
  cargo build --workspace --all-targets


# run `cargo check` on everything
check:
  cargo check --workspace --all-targets


# run all checks recommended before opening a PR
final-check: lint clippy
  cargo test --doc
  just test


# run code formatters
format:
  cargo fmt --all
  nixpkgs-fmt $(echo **.nix)


# run lints (git pre-commit hook)
lint:
  env NO_STASH=true $(git rev-parse --git-common-dir)/hooks/pre-commit


# run tests
test: build
  cargo test


# run and restart on changes
watch:
  env RUST_LOG=${RUST_LOG:-debug} cargo watch -x run


# run `cargo clippy` on everything
clippy:
  cargo clippy --workspace --all-targets -- --deny warnings --allow deprecated

# run `cargo clippy --fix` on everything
clippy-fix:
  cargo clippy --workspace --all-targets --fix



check-wasm:
  nix develop -c cargo check --target wasm32-unknown-unknown --package fedi-wasm

build-wasm:
  >&2 echo '⚠️ This is a development build of the wasm bundle, do not commit the output from this '
  ./scripts/build-wasm.sh --dev

release-wasm:
  ./scripts/build-wasm.sh --release

# FIXME: maybe we should just run the fixtures using the v0 nix shell,
# but us the normal environment to run `cargo test`
test-bridge-v0 testcase="":
   nix develop .#v0 --command ./scripts/test-bridge-v0.sh "{{testcase}}"

test-bridge-v1 testcase="":
  ./scripts/test-bridge-v1.sh "{{testcase}}"

test-bridge-all testcase="":
  ./scripts/test-bridge-all.sh "{{testcase}}"

# start mprocs with a dev federation setup
mprocs:
  ./scripts/mprocs.sh

# build the bridge for ui/native (android + ios + typescript bindings)
build-bridge:
  ./scripts/bridge/build.sh

# build only the android bridge artifacts for ui/native
build-bridge-android:
  nix develop --ignore-environment --command ./scripts/bridge/build-bridge-android.sh

# build only the ios bridge artifacts for ui/native
build-bridge-ios:
  # note: can't use --ignore-environment as it uses globally installed xcode
  nix develop .#xcode --command ./scripts/bridge/build-bridge-ios.sh

# install UI dependencies
build-ui-deps:
  nix develop --command ./scripts/ui/build-deps.sh

# generates a standard production release APK for @fedi/native
build-production-apk:
  nix develop --command ./scripts/ui/build-production-apk.sh

# generates a signed xcode release archive and uploads to testflight
deploy-to-testflight:
  nix develop .#xcode --command ./scripts/ui/deploy-to-testflight.sh

# generates a standard production release AAB for @fedi/native and uploads it to the Google Play Internal Testing track
deploy-to-google-play:
  nix develop --command ./scripts/ui/deploy-to-google-play.sh

# bumps the npm + react-native versions for @fedi/native
bump-version-native-ui:
  nix develop --command ./scripts/ui/bump-version-native.sh

# generate typescript bindings for the bridge
generate-bridge-bindings:
  ./scripts/bridge/ts-bindgen.sh

# start dev UI (native + pwa). Use `just run-dev-ui interactive` for build options
run-dev-ui mode="default":
  export MODE={{mode}} && ./scripts/ui/run-dev-ui.sh

# installs the xcodes tool and installs a version of Xcode.app
install-xcode:
  ./scripts/install-xcode.sh

# Builds an APK for a variant of the android app (Fedi Nightly) meant for
# nightly dev builds
build-nightly-apk:
  ./scripts/ui/build-nightly-apk.sh


# run `semgrep`
semgrep:
  env SEMGREP_ENABLE_VERSION_CHECK=0 \
    semgrep --error --config .config/semgrep.yaml


# check typos
[no-exit-message]
typos *PARAMS:
  #!/usr/bin/env bash
  set -eo pipefail

  export FLAKEBOX_GIT_LS
  FLAKEBOX_GIT_LS="$(git ls-files)"
  export FLAKEBOX_GIT_LS_TEXT
  FLAKEBOX_GIT_LS_TEXT="$(echo "$FLAKEBOX_GIT_LS" | grep -v -E "^db/|\.(png|ods|jpg|jpeg|woff2|keystore|wasm|ttf|jar|ico)\$")"


  if ! echo "$FLAKEBOX_GIT_LS_TEXT" | typos {{PARAMS}} --stdin-paths; then
    >&2 echo "Typos found: Valid new words can be added to '.typos.toml'"
    return 1
  fi

# fix all typos
[no-exit-message]
typos-fix-all:
  just typos -w

# THIS FILE IS AUTOGENERATED FROM FLAKEBOX CONFIGURATION
