/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function get_logs(): number;
export function fedimint_initialize(a: number): number;
export function fedimint_rpc(a: number, b: number, c: number, d: number): number;
export function fedimint_read_file(a: number, b: number): number;
export function fedimint_write_file(a: number, b: number, c: number): number;
export function ring_core_0_17_5_bn_mul_mont(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function rustsecp256k1_v0_8_1_context_create(a: number): number;
export function rustsecp256k1_v0_8_1_context_destroy(a: number): void;
export function rustsecp256k1_v0_8_1_default_illegal_callback_fn(a: number, b: number): void;
export function rustsecp256k1_v0_8_1_default_error_callback_fn(a: number, b: number): void;
export function rustsecp256k1zkp_v0_7_0_default_illegal_callback_fn(a: number, b: number): void;
export function rustsecp256k1zkp_v0_7_0_default_error_callback_fn(a: number, b: number): void;
export function rustsecp256k1_v0_6_1_context_create(a: number): number;
export function rustsecp256k1_v0_6_1_context_destroy(a: number): void;
export function rustsecp256k1_v0_6_1_default_illegal_callback_fn(a: number, b: number): void;
export function rustsecp256k1_v0_6_1_default_error_callback_fn(a: number, b: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function wasm_bindgen__convert__closures__invoke1_mut__hf9468372f05d0c69(a: number, b: number, c: number, d: number): void;
export function wasm_bindgen__convert__closures__invoke0_mut__h5315baf25b532075(a: number, b: number): void;
export function wasm_bindgen__convert__closures__invoke1_mut__h09f8e95eae18a864(a: number, b: number, c: number): void;
export function wasm_bindgen__convert__closures__invoke1_mut__hcdf9301817a70b7f(a: number, b: number, c: number): void;
export function wasm_bindgen__convert__closures__invoke0_mut__h62a77050ef2881f6(a: number, b: number): void;
export function __wbindgen_free(a: number, b: number): void;
export function __wbindgen_exn_store(a: number): void;
export function wasm_bindgen__convert__closures__invoke2_mut__h88ad8b4295ba9092(a: number, b: number, c: number, d: number): void;
