/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function get_logs(): number;
export function fedimint_initialize(a: number): number;
export function fedimint_rpc(a: number, b: number, c: number, d: number): number;
export function fedimint_read_file(a: number, b: number): number;
export function fedimint_write_file(a: number, b: number, c: number): number;
export function ring_core_0_17_5_bn_mul_mont(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function rustsecp256k1_v0_8_1_context_create(a: number): number;
export function rustsecp256k1_v0_8_1_context_destroy(a: number): void;
export function rustsecp256k1_v0_8_1_default_illegal_callback_fn(a: number, b: number): void;
export function rustsecp256k1_v0_8_1_default_error_callback_fn(a: number, b: number): void;
export function rustsecp256k1zkp_v0_7_0_default_illegal_callback_fn(a: number, b: number): void;
export function rustsecp256k1zkp_v0_7_0_default_error_callback_fn(a: number, b: number): void;
export function rustsecp256k1_v0_6_1_context_create(a: number): number;
export function rustsecp256k1_v0_6_1_context_destroy(a: number): void;
export function rustsecp256k1_v0_6_1_default_illegal_callback_fn(a: number, b: number): void;
export function rustsecp256k1_v0_6_1_default_error_callback_fn(a: number, b: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function wasm_bindgen__convert__closures__invoke1_mut__hb7980122161155c8(a: number, b: number, c: number, d: number): void;
export function wasm_bindgen__convert__closures__invoke1_mut__h0751d041da87eae3(a: number, b: number, c: number): void;
export function wasm_bindgen__convert__closures__invoke0_mut__hd92472798f6590ce(a: number, b: number): void;
export function wasm_bindgen__convert__closures__invoke1_mut__h0a7f6f3bc16f6768(a: number, b: number, c: number): void;
export function wasm_bindgen__convert__closures__invoke0_mut__hc31d0cdac305de3e(a: number, b: number): void;
export function wasm_bindgen__convert__closures__invoke1_mut__hcd844202aa5904c1(a: number, b: number, c: number): void;
export function wasm_bindgen__convert__closures__invoke0_mut__h739dd69c60e8d2be(a: number, b: number): void;
export function __wbindgen_free(a: number, b: number): void;
export function __wbindgen_exn_store(a: number): void;
export function wasm_bindgen__convert__closures__invoke2_mut__h8d021fcefbe45496(a: number, b: number, c: number, d: number): void;
