/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function get_logs(): number;
export function fedimint_initialize(a: number, b: number, c: number): number;
export function fedimint_rpc(a: number, b: number, c: number, d: number): number;
export function fedimint_read_file(a: number, b: number): number;
export function fedimint_write_file(a: number, b: number, c: number): number;
export function ffi_matrix_sdk_base_uniffi_contract_version(): number;
export function ffi_matrix_sdk_base_rustbuffer_alloc(a: number, b: number, c: number): void;
export function ffi_matrix_sdk_base_rustbuffer_from_bytes(a: number, b: number, c: number, d: number): void;
export function ffi_matrix_sdk_base_rustbuffer_free(a: number, b: number, c: number, d: number): void;
export function ffi_matrix_sdk_base_rustbuffer_reserve(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function ffi_matrix_sdk_base_rust_future_complete_u8(a: number, b: number): number;
export function ffi_matrix_sdk_base_rust_future_complete_i8(a: number, b: number): number;
export function ffi_matrix_sdk_base_rust_future_complete_u16(a: number, b: number): number;
export function ffi_matrix_sdk_base_rust_future_complete_i16(a: number, b: number): number;
export function ffi_matrix_sdk_base_rust_future_complete_i32(a: number, b: number): number;
export function ffi_matrix_sdk_base_rust_future_complete_i64(a: number, b: number): number;
export function ffi_matrix_sdk_base_rust_future_poll_f32(a: number, b: number, c: number): void;
export function ffi_matrix_sdk_base_rust_future_cancel_f32(a: number): void;
export function ffi_matrix_sdk_base_rust_future_complete_f32(a: number, b: number): number;
export function ffi_matrix_sdk_base_rust_future_free_f32(a: number): void;
export function ffi_matrix_sdk_base_rust_future_complete_f64(a: number, b: number): number;
export function ffi_matrix_sdk_base_rust_future_complete_rust_buffer(a: number, b: number, c: number): void;
export function ffi_matrix_sdk_base_rust_future_complete_void(a: number, b: number): void;
export function ffi_matrix_sdk_base_rust_future_poll_u8(a: number, b: number, c: number): void;
export function ffi_matrix_sdk_base_rust_future_poll_u16(a: number, b: number, c: number): void;
export function ffi_matrix_sdk_base_rust_future_poll_i8(a: number, b: number, c: number): void;
export function ffi_matrix_sdk_base_rust_future_poll_u32(a: number, b: number, c: number): void;
export function ffi_matrix_sdk_base_rust_future_poll_i32(a: number, b: number, c: number): void;
export function ffi_matrix_sdk_base_rust_future_poll_u64(a: number, b: number, c: number): void;
export function ffi_matrix_sdk_base_rust_future_poll_i64(a: number, b: number, c: number): void;
export function ffi_matrix_sdk_base_rust_future_poll_i16(a: number, b: number, c: number): void;
export function ffi_matrix_sdk_base_rust_future_poll_f64(a: number, b: number, c: number): void;
export function ffi_matrix_sdk_base_rust_future_poll_pointer(a: number, b: number, c: number): void;
export function ffi_matrix_sdk_base_rust_future_poll_rust_buffer(a: number, b: number, c: number): void;
export function ffi_matrix_sdk_base_rust_future_poll_void(a: number, b: number, c: number): void;
export function ffi_matrix_sdk_base_rust_future_complete_u32(a: number, b: number): number;
export function ffi_matrix_sdk_base_rust_future_complete_u64(a: number, b: number): number;
export function ffi_matrix_sdk_base_rust_future_complete_pointer(a: number, b: number): number;
export function ffi_matrix_sdk_base_rust_future_free_u8(a: number): void;
export function ffi_matrix_sdk_base_rust_future_free_u16(a: number): void;
export function ffi_matrix_sdk_base_rust_future_free_i8(a: number): void;
export function ffi_matrix_sdk_base_rust_future_free_u32(a: number): void;
export function ffi_matrix_sdk_base_rust_future_free_i32(a: number): void;
export function ffi_matrix_sdk_base_rust_future_free_u64(a: number): void;
export function ffi_matrix_sdk_base_rust_future_free_i64(a: number): void;
export function ffi_matrix_sdk_base_rust_future_free_i16(a: number): void;
export function ffi_matrix_sdk_base_rust_future_free_f64(a: number): void;
export function ffi_matrix_sdk_base_rust_future_free_pointer(a: number): void;
export function ffi_matrix_sdk_base_rust_future_free_rust_buffer(a: number): void;
export function ffi_matrix_sdk_base_rust_future_free_void(a: number): void;
export function ffi_matrix_sdk_base_rust_future_cancel_u8(a: number): void;
export function ffi_matrix_sdk_base_rust_future_cancel_u16(a: number): void;
export function ffi_matrix_sdk_base_rust_future_cancel_i8(a: number): void;
export function ffi_matrix_sdk_base_rust_future_cancel_u32(a: number): void;
export function ffi_matrix_sdk_base_rust_future_cancel_i32(a: number): void;
export function ffi_matrix_sdk_base_rust_future_cancel_u64(a: number): void;
export function ffi_matrix_sdk_base_rust_future_cancel_i64(a: number): void;
export function ffi_matrix_sdk_base_rust_future_cancel_i16(a: number): void;
export function ffi_matrix_sdk_base_rust_future_cancel_f64(a: number): void;
export function ffi_matrix_sdk_base_rust_future_cancel_pointer(a: number): void;
export function ffi_matrix_sdk_base_rust_future_cancel_rust_buffer(a: number): void;
export function ffi_matrix_sdk_base_rust_future_cancel_void(a: number): void;
export function ring_core_0_17_5_bn_mul_mont(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function rustsecp256k1zkp_v0_7_0_default_illegal_callback_fn(a: number, b: number): void;
export function rustsecp256k1zkp_v0_7_0_default_error_callback_fn(a: number, b: number): void;
export function rustsecp256k1_v0_8_1_context_create(a: number): number;
export function rustsecp256k1_v0_8_1_context_destroy(a: number): void;
export function rustsecp256k1_v0_8_1_default_illegal_callback_fn(a: number, b: number): void;
export function rustsecp256k1_v0_8_1_default_error_callback_fn(a: number, b: number): void;
export function rustsecp256k1_v0_6_1_context_create(a: number): number;
export function rustsecp256k1_v0_6_1_context_destroy(a: number): void;
export function rustsecp256k1_v0_6_1_default_illegal_callback_fn(a: number, b: number): void;
export function rustsecp256k1_v0_6_1_default_error_callback_fn(a: number, b: number): void;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function wasm_bindgen__convert__closures__invoke1_mut__h157a6d2077644be1(a: number, b: number, c: number, d: number): void;
export function wasm_bindgen__convert__closures__invoke1_mut__h9473a05403cdc766(a: number, b: number, c: number, d: number): void;
export function wasm_bindgen__convert__closures__invoke1_mut__hed1b663f3dbd6a69(a: number, b: number, c: number, d: number): void;
export function _dyn_core__ops__function__Fn_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h4020e3e8b429d2f7(a: number, b: number): void;
export function wasm_bindgen__convert__closures__invoke1__hb56582bfa9017be8(a: number, b: number, c: number): void;
export function wasm_bindgen__convert__closures__invoke0_mut__h98b3ddf81c763d88(a: number, b: number): void;
export function wasm_bindgen__convert__closures__invoke1_mut__h2d528cebdac2ef37(a: number, b: number, c: number): void;
export function wasm_bindgen__convert__closures__invoke0_mut__hca8cd1f67f7e45ff(a: number, b: number): void;
export function wasm_bindgen__convert__closures__invoke1_mut__h002c0432b425e06b(a: number, b: number, c: number): void;
export function wasm_bindgen__convert__closures__invoke0_mut__hd2f775b1486a2b13(a: number, b: number): void;
export function __wbindgen_free(a: number, b: number, c: number): void;
export function __wbindgen_exn_store(a: number): void;
export function wasm_bindgen__convert__closures__invoke2_mut__h9bb998a3c5818b5b(a: number, b: number, c: number, d: number): void;
