export type RpcMethodNames = keyof RpcMethods;
export type RpcPayload<M extends RpcMethodNames> = RpcMethods[M][0];
export type RpcResponse<M extends RpcMethodNames> = RpcMethods[M][1];

// used by generated code
declare const __opaque_type__: unique symbol; // https://blog.beraliv.dev/2021-05-07-opaque-type-in-typescript
export type Opaque<BaseType, TagName> = BaseType & {
  readonly [__opaque_type__]: TagName;
};

// this was auto generated by ts-bindgen.sh

export type AddressOrInvoice = "address" | "invoice";

export type Amount = Opaque<number, "fedimint_core::Amount">;

export interface BridgeLightningGateway {
  mintPubKey: Opaque<string, "XOnlyPublicKey">;
  nodePubKey: Opaque<string, "PublicKey">;
  api: string;
  active: boolean;
}

export type ErrorCode =
  | "initializationFailed"
  | "badRequest"
  | "invalidInvoice"
  | "invalidMnemonic"
  | "federationNotFound";

export type Event =
  | { Federation: { event: FedimintFederation } }
  | { Transaction: { event: TransactionEvent } }
  | { Log: { event: LogEvent } };

export type FederationId = Opaque<string, "FederationId">;

export interface FediConfig {
  client_config: any;
}

export interface FedimintFederation {
  id: FederationId;
  name: string;
  inviteCode: any;
  nodes: Array<{ url: string; name: string }>;
  balance: Amount;
  socialRecoveryActive: boolean;
  meta: Record<string, string>;
}

export type IncomingBitcoinTransactionStatus = "pending" | "complete";

export interface Invoice {
  paymentHash: string;
  amount: Amount;
  fee: Amount;
  description: string;
  invoice: string;
}

export interface LightningTransactionDetails {
  invoice: any;
  fee: Amount | null;
}

export interface LnurlSignedMessage {
  signature: string;
  pubkey: PublicKey;
}

export interface LogEvent {
  log: string;
}

export interface OfflineTransactionDetails {
  claimed: boolean;
}

export interface PayInvoiceResponse {
  preimage: string;
}

export type PeerId = number;

export type PublicKey = Opaque<string, "PublicKey">;

export type RecoveryId = Opaque<string, "RecoveryId">;

export interface RpcMethods {
  listTransactions: [
    { federationId: FederationId },
    Array<{
      id: string;
      createdAt: bigint;
      direction: TransactionDirection;
      amount: Amount;
      notes: string;
      lightning: LightningTransactionDetails | null;
      lnPayState: any;
      offline: OfflineTransactionDetails | null;
    }>
  ];
  updateTransactionNotes: [
    { federationId: FederationId; transactionId: string; notes: string },
    null
  ];
  joinFederation: [
    { connectString: string },
    {
      id: FederationId;
      name: string;
      inviteCode: any;
      nodes: Array<{ url: string; name: string }>;
      balance: Amount;
      socialRecoveryActive: boolean;
      meta: Record<string, string>;
    }
  ];
  listFederations: [
    {},
    Array<{
      id: FederationId;
      name: string;
      inviteCode: any;
      nodes: Array<{ url: string; name: string }>;
      balance: Amount;
      socialRecoveryActive: boolean;
      meta: Record<string, string>;
    }>
  ];
  generateInvoice: [
    { federationId: FederationId; amount: Amount; description: string },
    string
  ];
  decodeInvoice: [
    { invoice: string },
    {
      paymentHash: string;
      amount: Amount;
      fee: Amount;
      description: string;
      invoice: string;
    }
  ];
  payInvoice: [
    { federationId: FederationId; invoice: string },
    { preimage: string }
  ];
  generateAddress: [{ federationId: FederationId }, string];
  payAddress: [
    { federationId: FederationId; address: string; sats: bigint },
    string
  ];
  generateEcash: [{ federationId: FederationId; amount: Amount }, string];
  receiveEcash: [
    { federationId: FederationId; ecash: string },
    Opaque<number, "fedimint_core::Amount">
  ];
  validateEcash: [
    { federationId: FederationId; ecash: string },
    { valid: boolean; amount: Amount }
  ];
  addressOrInvoice: [
    { federationId: FederationId; input: string },
    "address" | "invoice"
  ];
  listGateways: [
    { federationId: FederationId },
    Array<{
      mintPubKey: Opaque<string, "XOnlyPublicKey">;
      nodePubKey: Opaque<string, "PublicKey">;
      api: string;
      active: boolean;
    }>
  ];
  switchGateway: [{ federationId: FederationId; nodePubkey: PublicKey }, null];
  getMnemonic: [{ federationId: FederationId }, Array<string>];
  recoverFromMnemonic: [
    { federationId: FederationId; mnemonic: Array<string> },
    string | null
  ];
  leaveFederation: [{ federationId: FederationId }, null];
  connectionString: [{ federationId: FederationId }, string];
  uploadBackupFile: [
    { federationId: FederationId; videoFilePath: string },
    string
  ];
  locateRecoveryFile: [{}, string];
  validateRecoveryFile: [{ federationId: FederationId; path: string }, boolean];
  recoveryQr: [{ federationId: FederationId }, { recoveryId: RecoveryId }];
  socialRecoveryApprovals: [
    { federationId: FederationId },
    {
      federationId: FederationId;
      approvals: Array<SocialRecoveryApproval>;
      remaining: number;
    }
  ];
  completeSocialRecovery: [{ federationId: FederationId }, string | null];
  socialRecoveryDownloadVerificationDoc: [
    { federationId: FederationId; recoveryId: RecoveryId },
    string | null
  ];
  approveSocialRecoveryRequest: [
    {
      federationId: FederationId;
      recoveryId: RecoveryId;
      peerId: PeerId;
      password: string;
    },
    null
  ];
  signLnurlMessage: [
    { message: string; federationId: string },
    { signature: string; pubkey: PublicKey }
  ];
  xmppCredentials: [
    { federationId: FederationId },
    { password: string; keypairSeed: string; username: string | null }
  ];
  backupXmppUsername: [{ federationId: FederationId; username: string }, null];
}

export interface SocialRecoveryApproval {
  guardianName: string;
  approved: boolean;
}

export interface SocialRecoveryEvent {
  federationId: FederationId;
  approvals: Array<SocialRecoveryApproval>;
  remaining: number;
}

export type TransactionDirection = "send" | "receive";

export interface TransactionEvent {
  federationId: FederationId;
  transaction: Transaction;
}

export interface Transaction {
  id: string;
  createdAt: bigint;
  direction: TransactionDirection;
  amount: Amount;
  notes: string;
  lightning: LightningTransactionDetails | null;
  lnPayState: any;
  offline: OfflineTransactionDetails | null;
}

export interface XmppCredentials {
  password: string;
  keypairSeed: string;
  username: string | null;
}
