export type RpcMethodNames = keyof RpcMethods;
export type RpcPayload<M extends RpcMethodNames> = RpcMethods[M][0];
export type RpcResponse<M extends RpcMethodNames> = RpcMethods[M][1];

// used by generated code
declare const __opaque_type__: unique symbol; // https://blog.beraliv.dev/2021-05-07-opaque-type-in-typescript
export type Opaque<BaseType, TagName> = BaseType & {
  readonly [__opaque_type__]: TagName;
};

// this was auto generated by ts-bindgen.sh

export type AddressOrInvoice = "address" | "invoice";

export type Amount = Opaque<number, "fedimint_api::Amount">;

export interface BitcoinTransactionDetails {
  address: string;
  txid: string;
  fee: Amount | null;
  incomingStatus: IncomingBitcoinTransactionStatus | null;
}

export interface BridgeLightningGateway {
  mintPubKey: Opaque<string, "XOnlyPublicKey">;
  nodePubKey: Opaque<string, "PublicKey">;
  api: string;
  active: boolean;
}

export type ErrorCode =
  | "initializationFailed"
  | "badRequest"
  | "invalidInvoice"
  | "invalidMnemonic";

export type Event =
  | { Federation: { event: FedimintFederation } }
  | { Transaction: { event: TransactionEvent } }
  | { SocialRecovery: { event: SocialRecoveryEvent } }
  | { RecoveryFileCreation: { event: RecoveryFileCreationEvent } }
  | { Log: { event: LogEvent } };

export interface FediConfig {
  client_config: any;
  username: string | null;
}

export interface FedimintFederation {
  name: string;
  connectInfo: any;
  nodes: Array<{ url: string; name: string }>;
  balance: Amount;
  socialRecoveryActive: boolean;
}

export type IncomingBitcoinTransactionStatus = "pending" | "complete";

export interface LightningTransactionDetails {
  invoice: any;
  fee: Amount | null;
}

export interface LnurlSignedMessage {
  signature: string;
  pubkey: PublicKey;
}

export interface LogEvent {
  log: string;
}

export interface OfflineTransactionDetails {
  claimed: boolean;
}

export type PeerId = number;

export type PublicKey = Opaque<string, "PublicKey">;

export interface RecoveryFileCreationEvent {
  federationId: string;
}

export type RecoveryId = Opaque<string, "RecoveryId">;

export interface RpcMethods {
  listTransactions: [
    { federationId: string },
    Array<{
      id: string;
      createdAt: bigint;
      direction: TransactionDirection;
      amount: Amount;
      notes: string;
      lightning: LightningTransactionDetails | null;
      bitcoin: BitcoinTransactionDetails | null;
      offline: OfflineTransactionDetails | null;
    }>
  ];
  updateTransactionNotes: [
    { federationId: string; transactionId: string; notes: string },
    null
  ];
  joinFederation: [
    { connectString: string },
    {
      name: string;
      connectInfo: any;
      nodes: Array<{ url: string; name: string }>;
      balance: Amount;
      socialRecoveryActive: boolean;
    }
  ];
  listFederations: [
    {},
    Array<{
      name: string;
      connectInfo: any;
      nodes: Array<{ url: string; name: string }>;
      balance: Amount;
      socialRecoveryActive: boolean;
    }>
  ];
  generateInvoice: [
    { federationId: string; amount: Amount; description: string },
    string
  ];
  decodeInvoice: [{ invoice: string }, string];
  payInvoice: [{ federationId: string; invoice: string }, null];
  generateAddress: [{ federationId: string }, string];
  payAddress: [{ federationId: string; address: string; sats: bigint }, string];
  generateEcash: [{ federationId: string; amount: Amount }, string];
  receiveEcash: [
    { federationId: string; ecash: string },
    Opaque<number, "fedimint_api::Amount">
  ];
  validateEcash: [
    { federationId: string; ecash: string },
    { valid: boolean; amount: Amount }
  ];
  addressOrInvoice: [
    { federationId: string; input: string },
    "address" | "invoice"
  ];
  listGateways: [
    { federationId: string },
    Array<{
      mintPubKey: Opaque<string, "XOnlyPublicKey">;
      nodePubKey: Opaque<string, "PublicKey">;
      api: string;
      active: boolean;
    }>
  ];
  switchGateway: [{ federationId: string; nodePubkey: PublicKey }, null];
  getMnemonic: [{ federationId: string }, Array<string>];
  recoverFromMnemonic: [
    { federationId: string; mnemonic: Array<string> },
    string | null
  ];
  leaveFederation: [{ federationId: string }, null];
  uploadBackupFile: [{ federationId: string; videoFilePath: string }, string];
  locateRecoveryFile: [{}, string];
  validateRecoveryFile: [{ federationId: string; path: string }, boolean];
  recoveryQr: [{ federationId: string }, { recoveryId: RecoveryId }];
  socialRecoveryApprovals: [
    { federationId: string },
    {
      federationId: string;
      approvals: Array<SocialRecoveryApproval>;
      remaining: number;
    }
  ];
  completeSocialRecovery: [{ federationId: string }, string | null];
  socialRecoveryDownloadVerificationDoc: [
    { federationId: string; recoveryId: RecoveryId },
    string | null
  ];
  approveSocialRecoveryRequest: [
    {
      federationId: string;
      recoveryId: RecoveryId;
      peerId: PeerId;
      password: string;
    },
    null
  ];
  lnurlSignMessage: [
    { message: string; federationId: string },
    { signature: string; pubkey: PublicKey }
  ];
  xmppCredentials: [{ federationId: string }, { password: string }];
  backupXmppUsername: [{ federationId: string; username: string }, null];
}

export interface SocialRecoveryApproval {
  guardianName: string;
  approved: boolean;
}

export interface SocialRecoveryEvent {
  federationId: string;
  approvals: Array<SocialRecoveryApproval>;
  remaining: number;
}

export type TransactionDirection = "send" | "receive";

export interface TransactionEvent {
  federationId: string;
  transaction: Transaction;
}

export interface Transaction {
  id: string;
  createdAt: bigint;
  direction: TransactionDirection;
  amount: Amount;
  notes: string;
  lightning: LightningTransactionDetails | null;
  bitcoin: BitcoinTransactionDetails | null;
  offline: OfflineTransactionDetails | null;
}

export interface XmppCredentials {
  password: string;
    keypairSeed: string;
}
