[package]
name = "v1-social"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
bitcoin = "0.29.2"
fedimint-core = { git = "https://github.com/fedimint/fedimint", rev = "d3c3c91c8b54f289c09f80f38c6139136b9d8bdf" }
serde = { version = "1.0.142", features = [ "derive" ] }
fedi-social-client-v1 = { workspace = true }
threshold_crypto = { workspace = true }
v1-rocksdb = { path = "../v1-rocksdb" }
