#!/usr/bin/env bash

set -eu

export tmp_file="$1.tmp"

if [ -z "${IN_NIX_SHELL:-}" ]; then
  >&2 echo "Workaround: restart in 'nix develop' shell"
  exec nix develop .#lint --command "$0" "$@"
fi

function rm_tmp_file {
  rm -f "$tmp_file"
}

trap rm_tmp_file EXIT

# Sanitize file first, by removing leading lines that are empty or start with a hash,
# as `convco` currently does not do it automatically (but git will)
# TODO: next release of convco should be able to do it automatically
echo -n "" > "$tmp_file"
while read -r line ; do
  # skip any initial comments (possibly from previous run)
  if [ -z "${body_detected:-}" ] && { [[ "$line" =~ ^#.*$ ]] || [ "$line" == "" ]; }; then
    continue
  fi
  body_detected="true"

  echo "$line" >> "$tmp_file"
done < "$1"

if ! convco check --from-stdin < "$tmp_file" ; then
   >&2 echo "Use git recommit <args> to fix your commit"
  exit 1
fi
