require_relative '../../node_modules/react-native/scripts/react_native_pods'
require_relative '../../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false

target 'FediReactNative' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => true,
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => FlipperConfiguration.enabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'OpenSSL-Universal', :modular_headers => true, :configurations => ['Release']

  target 'FediReactNativeTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )

    # This line was previously uncommented and required however this function
    # in /node_modules/react-native/scripts/react_native_pods.rb currently
    # targets 11.0 as a minimum but the build is failing for some pods so
    # we need to bump the target here to 12.0 so the function is copied
    # exactly as-is here with the deployment target version changed
    # __apply_Xcode_12_5_M1_post_install_workaround(installer)
    # -----------------------------------------
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # ensure IPHONEOS_DEPLOYMENT_TARGET is at least 12.0
        deployment_target = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f
        should_upgrade = deployment_target < 12.0 && deployment_target != 0.0
        if should_upgrade
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
        end
      end
    end
    time_header = "#{Pod::Config.instance.installation_root.to_s}/Pods/RCT-Folly/folly/portability/Time.h"
    `sed -i -e  $'s/ && (__IPHONE_OS_VERSION_MIN_REQUIRED < __IPHONE_10_0)//' #{time_header}`
    # -----------------------------------------
  end
end
