[package]
name = "v0-rocksdb"
version = "0.1.2"
edition = "2021"

[dependencies]
fedimint-core = { git = "https://x-access-token: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@github.com/fedibtc/fedimint-fedi", branch = "rel-a05" }
fedimint-client-v0 = { workspace = true }
# fedimint-core = { package = "fedimint-core", path = "../../../fedimint/fedimint-core" }
