#!/usr/bin/env bash

set -e
REPO_ROOT=$(git rev-parse --show-toplevel)

if [[ "$SKIP_IOS_BUILD" == "1" ]]; then
    echo "iOS build skipped"
    exit 0
fi

# This script allows the user to select an iOS device from a list generated by 
# the "xcrun xctrace list devices" command. The list includes both physical devices 
# connected to the machine and simulators. Once the user selects a device, the script 
# extracts the device ID, which can then be used to run commands specifically for that device.
devices=()
xcrunDevicesList=$(nix develop .#cross --command xcrun xctrace list devices)
while IFS= read -r line; do
    devices+=("$line")
done < <(echo "$xcrunDevicesList" | grep -Eo '.*\([0-9A-Fa-f-]+\)$')

# If no devices are found, exit
if [ ${#devices[@]} -eq 0 ]; then
    echo "No ios devices found"
    exit 1
fi

# Set the default choice to the last device
defaultChoice=${#devices[@]}

# allow the user to select from the list
if [[ "$SELECT_IOS_DEVICE" == "1" ]]; then
    echo "Select a device:"
    for i in "${!devices[@]}"; do 
        echo "$((i+1))) ${devices[$i]}"
    done

    # Prompt for user input and use the default choice if none is given
    read -p "Enter choice: " choice
    choice=${choice:-$defaultChoice}

    selectedDevice=${devices[$((choice-1))]}  # adjust for 0-indexing

    echo "You selected device: $selectedDevice"
else
    # If SELECT_IOS_DEVICE is 0, select the default device without prompting the user
    selectedDevice=${devices[$((defaultChoice-1))]}
fi

# Extract the device ID
FEDI_DEVICE_ID=$(echo "$selectedDevice" | sed -n -E 's/.*\(([^)]+)\).*/\1/p')

# $REPO_ROOT/scripts/enforce-nix.sh

cd $REPO_ROOT/ui/native
echo "Building & installing ios app bundle"

# Launch ios
nix develop .#cross --command npx react-native run-ios --destination arch=x86_64 --udid $FEDI_DEVICE_ID
# Start logging
nix develop .#cross --command npx react-native log-ios
