[package]
name = "device-registration"
version = "0.3.0"
edition = "2021"

[dependencies]
fedimint-core = { workspace = true }

anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
bip39 = { version = "2.0.0", features = ["rand"] }
tracing = { workspace = true }
tokio = { workspace = true, features = ["time", "macros"] }
reqwest = { workspace = true }
fedi-common = { path = "../fedi-common" }
fedi-rpc-types = { path = "../fedi-rpc-types" }
