# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight from CI"
  lane :beta_ci do
    setup_ci
    match(
      type: 'appstore',
      git_url: 'https://x-access-token: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@github.com/fedibtc/fedi-alpha-react-native-certs',
      storage_mode: 'git',
      api_key_path: 'fastlane/../decoded-asc-api-key-credentials.json'
    )
    # these steps are the same as standard beta lane
    build_app(
      workspace: "FediReactNative.xcworkspace",
      scheme: "FediReactNative",
      export_options: {
        provisioningProfiles: {
          "org.fedi.alpha" => "match AppStore org.fedi.alpha"
        }
      }
    )
    changelog_from_git_commits
    upload_to_testflight(
      api_key_path: 'fastlane/../decoded-asc-api-key-credentials.json'
    )
  end
  
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "FediReactNative.xcodeproj")
    build_app(
      workspace: "FediReactNative.xcworkspace",
      scheme: "FediReactNative",
      export_options: {
        provisioningProfiles: {
          "org.fedi.alpha" => "match AppStore org.fedi.alpha"
        }
      }
    )
    changelog_from_git_commits
    upload_to_testflight(
      api_key_path: 'fastlane/../decoded-asc-api-key-credentials.json'
    )
  end
  
  desc "Create a release build"
  lane :build_release do
    build_app(
      workspace: "FediReactNative.xcworkspace",
      scheme: "FediReactNative",
      export_options: {
        provisioningProfiles: {
          "org.fedi.alpha" => "match AppStore org.fedi.alpha"
        }
      }
    )
  end

  # Run this on a new device that needs to create signed releases
  # Existing certificates will automatically be downloaded from Github
  desc "Check for signing certificates"
  lane :check_appstore_certs do
    match(
      type: 'appstore',
      git_url: 'https://x-access-token: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@github.com/fedibtc/fedi-alpha-react-native-certs',
      storage_mode: 'git',
      api_key_path: 'fastlane/../decoded-asc-api-key-credentials.json'
    )
  end
end
