# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight from CI"
  lane :beta_ci do
    # these 2 extra steps are so CI can download signing certs from Github repo (see Matchfile)
    setup_ci
    match(type: 'appstore')
    # these steps are the same as standard beta lane
    build_app(
      workspace: "FediReactNative.xcworkspace",
      scheme: "FediReactNative",
      export_options: {
        provisioningProfiles: {
          "org.fedi.alpha" => "match AppStore org.fedi.alpha"
        }
      }
    )
    changelog_from_git_commits
    upload_to_testflight(
      api_key_path: 'fastlane/../decoded-asc-api-key-credentials.json'
    )
  end
  
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "FediReactNative.xcodeproj")
    build_app(
      workspace: "FediReactNative.xcworkspace",
      scheme: "FediReactNative",
      export_options: {
        provisioningProfiles: {
          "org.fedi.alpha" => "match AppStore org.fedi.alpha"
        }
      }
    )
    changelog_from_git_commits
    upload_to_testflight(
      api_key_path: 'fastlane/../decoded-asc-api-key-credentials.json'
    )
  end

  # This lane should rarely be needed but if you comment all lines in Matchfile
  # you can use this to generate new signing certificates and automatically 
  # upload them to Github
  desc "Check for signing certificates"
  lane :check_appstore_certs do
    match(type: 'appstore')
  end
end
