[package]
name = "fedi-ffi"
version = "0.1.2"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]
name = "fediffi"

[dependencies]
mint-client = { workspace = true }
fedimint-core = { workspace = true }
fedimint-client = { workspace = true }
fedi-social-client = { path = "../../fedi-social-client" }
fedimint-client-fedi = { path = "../../fedimint-client-fedi" }
fedimint-derive-secret = { workspace = true }

bip39 = { git = "https://github.com/justinmoon/rust-bip39" }
anyhow = "1"
serde = { version = "1.0.142", features = [ "derive" ] }
serde_json = "1.0.79"
rand = "0.8.5"
bitcoin = "0.29.2"
lazy_static = "1.4.0"
lightning-invoice = "0.21.0"
futures = "0.3"
tracing = "0.1.26"
reqwest = { version = "0.11.12", features = [ "json" ], default-features = false }
tokio = {version = "1.0", features = ["sync"]}
thiserror = "1.0.37"
hex = "0.4.3"
macro_rules_attribute = "0.1.3"
ts-rs = { git = "https://github.com/maan2003/ts-rs", branch = "fix-type-struct-zero" }
async-trait = "0.1.64"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
electrum-client = "0.12.0"
fedimint-rocksdb = { workspace = true }
tokio = {version = "1.0", features = ["full"]}
tracing-subscriber = { version = "0.3.1", features = [ "env-filter", "json" ] }
reqwest = { version = "0.11.12", features = [ "json", "rustls-tls" ], default-features = false }
uniffi_macros = { version = "0.21.0", features = ["builtin-bindgen"] }
uniffi = { version = "0.21.0", features = ["builtin-bindgen"] }

[build-dependencies]
uniffi_build = { version = "0.21.0", features = ["builtin-bindgen"] }

[dev-dependencies]
tempfile = "3.3.0"

# [target.'cfg(target_os = "macos")'.dependencies]
# fedimint-logging = { workspace = true }

# [target.'cfg(target_os = "linux")'.dependencies]
# fedimint-logging = { workspace = true }
