# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build a new apk to debug for production (apk can be found at /android/build/outputs/apk/production/debug/app-production-debug.apk)"
  lane :build_debug do
    gradle(task: 'clean')
    gradle(
      task: 'assemble',
      flavor: 'production',
      build_type: 'Debug'
    )
  end

  desc "Increment the versionCode in build.gradle"
  lane :increment_version_code do
    android_set_version_code(
      gradle_file: './app/build.gradle'
    )
  end

  desc "Build a new app APK to release for production"
  lane :build_production_apk do
    gradle(
      task: 'assemble',
      flavor: 'production',
      build_type: 'Release'
    )
  end

  desc "Build a new app bundle to release for production"
  lane :build_production do
    gradle(task: 'clean')
    gradle(
      task: 'bundle',
      flavor: 'production',
      build_type: 'Release'
    )
  end

  desc "Build a new app bundle to release for special deployment (Bitcoin Lake)"
  lane :build_bitcoin_lake do
    gradle(task: 'clean')
    gradle(
      task: 'bundle',
      flavor: 'bitcoinlake',
      build_type: 'Release'
    )
  end

  desc "Upload the latest build for internal testing"
  lane :upload_internal_build do
    upload_to_play_store(
      track: 'internal',
      package_name: 'com.fedimintreactnative',
      aab: './app/build/outputs/bundle/productionRelease/app-production-release.aab',
      release_status: 'draft',
      skip_upload_apk: true
    )
  end

  desc "Upload the latest build for beta testing"
  lane :upload_beta_build_production do
    upload_to_play_store(
      track: 'beta',
      package_name: 'com.fedimintreactnative',
      aab: './app/build/outputs/bundle/productionRelease/app-production-release.aab',
      skip_upload_apk: true
    )
  end

  desc "Upload the latest build for special deployment (Bitcoin Lake)"
  lane :upload_beta_build_bitcoin_lake do
    upload_to_play_store(
      track: 'beta',
      package_name: 'com.fedimintreactnative.bitcoinlake',
      aab: './app/build/outputs/bundle/bitcoinlakeRelease/app-bitcoinlake-release.aab',
      skip_upload_apk: true
    )
  end

  desc "Submit a new internal build"
  lane :internal do
    increment_version_code
    build_production
    upload_internal_build
  end

  desc "Submit a new beta build"
  lane :beta do
    increment_version_code
    build_production
    upload_beta_build_production
  end

  desc "Submit a new beta build for special deployment (Bitcoin Lake)"
  lane :beta_bitcoin_lake do
    increment_version_code
    build_bitcoin_lake
    upload_beta_build_bitcoin_lake
  end

  # desc "Deploy a new version to the Google Play"
  # lane :deploy do
  #   gradle(task: "clean assembleRelease")
  #   upload_to_play_store
  # end
end
