[package]
name = "fedi-db-tool"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fedimint-rocksdb = { workspace = true }
fedimint-core = { workspace = true }
fedi-db-dump = { path = "../fedi-db-dump" }
clap = { version = "4.5.4", features = ["derive"] }
tokio = { version = "1.37.0", features = ["full"] }
anyhow = "1.0.81"
