[package]
name = "calculator-ffi"
version = "0.1.2"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]
name = "calculatorffi"


[dependencies]
#mint-client = { git = "https://github.com/fedimint/fedimint" }
#fedimint-api = { git = "https://github.com/fedimint/fedimint" }
#fedimint-core = { git = "https://github.com/fedimint/fedimint" }
#fedimint-sled = { git = "https://github.com/fedimint/fedimint" }
mint-client = { git = "https://github.com/fedimint/fedimint", rev = "0b97c298a88da037e5b87bfe0b2203773251b610" }
fedimint-api = { git = "https://github.com/fedimint/fedimint", rev = "0b97c298a88da037e5b87bfe0b2203773251b610" }
fedimint-core = { git = "https://github.com/fedimint/fedimint", rev = "0b97c298a88da037e5b87bfe0b2203773251b610" }
fedimint-sled = { git = "https://github.com/fedimint/fedimint", rev = "0b97c298a88da037e5b87bfe0b2203773251b610" }

anyhow = "1"
serde = { version = "1.0.142", features = [ "derive" ] }
serde_json = "1.0.79"
rand = "0.8.5"
bitcoin = "0.29.1"
lazy_static = "1.4.0"
lightning-invoice = "0.20.0"
futures = "0.3"
tracing = "0.1.26"
electrum-client = "0.12.0"
reqwest = { version = "0.11.12", features = [ "json", "rustls-tls" ], default-features = false }
tracing-subscriber = { version = "0.3.1", features = [ "env-filter" ] }
sled = "0.34.6"
tokio = {version = "1.0", features = ["full"]}
thiserror = "1.0.37"

uniffi_macros = { version = "0.21.0", features = ["builtin-bindgen"] }
uniffi = { version = "0.21.0", features = ["builtin-bindgen"] }

[build-dependencies]
uniffi_build = { version = "0.21.0", features = ["builtin-bindgen"] }

# [target.'cfg(target_os = "ios")'.dependencies]
# tracing-oslog = "0.1.2"

[target.'cfg(target_os = "android")'.dependencies]
paranoid-android = { git = "https://github.com/justinmoon/paranoid-android", branch="c_char" }