name: Bump patch version
on:
    workflow_dispatch:
    # runs on release/X.Y.Z branches but not release/X.Y branches
    # push:
    #     branches:
    #         - 'release/**.**.**'
    #         - '!release/**.**'
jobs:
    bump-version:
        name: Update version to match release branch
        runs-on: buildjet-2vcpu-ubuntu-2204
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: '16.18.X'

            - name: Bump version
              id: versioning
              run: |
                  git config --global user.email "dev@fedibtc.com"
                  git config --global user.name "Fedi Dev CI"
                  RELEASE_BRANCH_VERSION="${GITHUB_REF##*/}"
                  CURRENT_VERSION="$(npm pkg get version | sed 's/"//g')"
                  if [[ "$CURRENT_VERSION" != "$RELEASE_BRANCH_VERSION" ]] && [[ "$RELEASE_BRANCH_VERSION" == *"."* ]];
                  then
                      npm version --allow-same-version --force $RELEASE_BRANCH_VERSION
                      npx react-native-version --amend
                      git push
                      NEW_VERSION="$(npm pkg get version | sed 's/"//g')"
                      echo "Bumped version from $CURRENT_VERSION to $NEW_VERSION"
                  else
                      echo 'No version bump needed'
                  fi
