name: Check PRs for potential conflicts
# This workflow runs every time a Pull Request is opened, updated, or reopened
on:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    name: potential-conflicts-checker
    runs-on: ubuntu-latest
    steps:
      - uses: outsideris/potential-conflicts-checker-action@0.1.0
        with:
          ghToken: ${{ secrets.GITHUB_TOKEN }}
