name: Deploy Public APK to Github
env:
    TEST_RELEASE_ID: '179645236'
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_APK_PROJECT_ID }}
on:
    workflow_dispatch:
    release:
        # these events will not fire for draft releases
        types: [published, edited]

jobs:
    deploy-public-apk:
        runs-on: [self-hosted, linux]
        steps:
            - name: Checkout script in repo
              uses: actions/checkout@v4

            - name: Run publish-release
              uses: actions/github-script@v7
              id: publish-release
              env:
                  RELEASE_ID: ${{ github.event.release.id || env.TEST_RELEASE_ID }}
              with:
                  github-token: ${{ secrets.DOWNLOAD_APK_ACCESS_TOKEN }}
                  result-encoding: string
                  script: |
                      const script = require('./scripts/ci/deploy-public-apk.js')
                      await script({github, context, core})

            - uses: cachix/install-nix-action@v30
              with:
                  nix_path: nixpkgs=channel:nixos-23.05

            - uses: cachix/cachix-action@v15
              with:
                  name: fedibtc
                  authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

            - name: Deploy APK to Vercel
              id: deploy
              run: nix develop .#vercel -c env VERCEL_TOKEN=${{ secrets.VERCEL_TOKEN }} ./scripts/ci/vercel-apk.sh
