name: Publish Android App to Play Dev Console
on:
    workflow_dispatch:
    push:
        branches:
            - 'release/**'
jobs:
    release-android:
        name: Build and release Android app
        runs-on: buildjet-2vcpu-ubuntu-2204
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2
            - name: Setup JDK
              uses: actions/setup-java@v1
              with:
                  java-version: 11
            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: '16.18.X'
            - name: Setup Ruby
              uses: ruby/setup-ruby@v1
              with:
                  ruby-version: '2.7.5'
            - name: Install packages
              run: npm install
            - name: Install Fastlane
              run: cd android && bundle install && cd ..
            - name: Execute Fastlane command
              run: cd android && bundle exec fastlane internal
