name: Deploy to TestFlight
on:
    workflow_dispatch:

defaults:
    run:
        working-directory: ui/native

jobs:
    release-ios:
        name: Build iOS app and upload to TestFlight
        runs-on: self-hosted
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2
              with:
                  submodules: true

            - uses: cachix/install-nix-action@v20
              with:
                  nix_path: nixpkgs=channel:nixos-22.05

            - uses: cachix/cachix-action@v12
              with:
                  name: fedibtc
                  authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: '16.18.X'

            - name: Build bridge
              run: |
                  npm run build-bridge-ios

            - name: Install Node dependencies
              run: npm ci --cache .npm

            - name: Install pods
              run: cd ios && pod install && cd ..

            - name: Generate JSON credentials file
              run: |
                  mkdir tmp
                  echo ${{ secrets.ASC_API_KEY_JSON_CREDENTIALS_ENCODED }} >> ./tmp/asc-api-key-credentials.txt
                  base64 --decode ./tmp/asc-api-key-credentials.txt >> ./ios/decoded-asc-api-key-credentials.json
                  rm -rf ./tmp

            - name: Install Fastlane
              run: cd ios && bundle install && cd ..

            - name: Execute fastlane beta lane for CI
              env:
                  MATCH_PASSWORD: 'fedimint'
              run: |
                  cd ios && bundle exec fastlane beta_ci && cd ..
