name: Deploy to TestFlight
on:
    workflow_dispatch:

jobs:
    release-ios:
        name: Build iOS app and upload to TestFlight
        runs-on: macos-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2
              with:
                  submodules: true

            - name: Cache
              uses: actions/cache@v3
              env:
                  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 15
              with:
                  path: |
                      ~/.cargo/registry
                      ~/.cargo/git
                      ./bridge/target
                  key: ${{ runner.os }}

            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: nightly
                  override: true
                  components: rustfmt, clippy

            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: '16.18.X'

            - name: Build bridge
              env:
                  FM_ROCKSDB: true
              run: |
                  npm run build-bridge-ios

            - name: Install Node dependencies
              run: npm ci --cache .npm

            - name: Setup Ruby
              uses: ruby/setup-ruby@v1
              with:
                  ruby-version: '2.7.5'

            - name: Install pods
              run: cd ios && pod install && cd ..

            - name: Generate JSON credentials file
              run: |
                  mkdir tmp
                  echo ${{ secrets.ASC_API_KEY_JSON_CREDENTIALS_ENCODED }} >> ./tmp/asc-api-key-credentials.txt
                  base64 --decode ./tmp/asc-api-key-credentials.txt >> ./ios/decoded-asc-api-key-credentials.json
                  rm -rf ./tmp

            - name: Install Fastlane
              run: cd android && bundle install && cd ..

            - name: Execute fastlane beta lane for CI
              env:
                  MATCH_PASSWORD: 'fedimint'
              run: |
                  cd ios && bundle exec fastlane beta_ci && cd ..
