name: 'Nix'

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the "main" branch
    push:
        branches: ['main', 'master', 'devel']
        paths-ignore:
            - 'ui/**'
    pull_request: {}

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    precheck:
        name: 'Check for non-UI file changes'
        runs-on: [self-hosted, linux]
        outputs:
            IS_PUSH_TO_MASTER: ${{ steps.check-event.outputs.IS_PUSH_TO_MASTER }}
            HAS_NON_UI_CHANGES: ${{ steps.check-changes.outputs.HAS_NON_UI_CHANGES }}
        steps:
            - name: Determine event type
              id: check-event
              run: |
                  IS_PUSH_TO_MASTER=0
                  if [[ "${{ github.event_name }}" == 'push' && \
                      "${{ github.ref }}" == 'refs/heads/master' ]]; then
                    IS_PUSH_TO_MASTER=1
                  fi
                  echo "IS_PUSH_TO_MASTER=$IS_PUSH_TO_MASTER" >> $GITHUB_OUTPUT
            - name: Check out code
              uses: actions/checkout@v3
              with:
                  ref: ${{ github.event.pull_request.base.ref }}
                  fetch-depth: 1
            - name: Check for changes outside 'ui/**'
              id: check-changes
              run: |
                  git fetch origin ${{ github.event.pull_request.head.sha }} 
                  FILES_CHANGED=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
                  HAS_NON_UI_CHANGES=0
                  for file in $FILES_CHANGED; do
                    if [[ ! $file == ui/* ]]; then
                      HAS_NON_UI_CHANGES=1
                      break
                    fi
                  done
                  echo "HAS_NON_UI_CHANGES=$HAS_NON_UI_CHANGES" >> $GITHUB_OUTPUT

    lint:
        name: 'Lint'
        needs: precheck
        if: >
            needs.precheck.outputs.HAS_NON_UI_CHANGES == '1' ||
            needs.precheck.outputs.IS_PUSH_TO_MASTER == '1'
        runs-on: [self-hosted, linux]
        timeout-minutes: 5
        steps:
            - uses: actions/checkout@v3
            - uses: cachix/install-nix-action@v20
              with:
                  nix_path: nixpkgs=channel:nixos-22.05
            - uses: cachix/cachix-action@v12
              with:
                  name: fedibtc
                  authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
              continue-on-error: true

            # run the same check that git `pre-commit` hook would, just in case
            - name: Commit check
              run: nix develop --ignore-environment .#lint --command ./misc/git-hooks/pre-commit

    # all the derivations that are based on the whole workspace
    build-workspace:
        strategy:
          matrix:
            host:
              - linux
              - macos
            include:
              - host: linux
                runs-on: [self-hosted, linux]
                test-bridge: testBridgeAllNoV0
                run-tests: true
              - host: macos
                runs-on: [self-hosted, macos, arm64]
                # only current on macos, slow and hitting irrelevant issues
                test-bridge: testBridgeCurrent
                run-tests: false

        name: "Build workspace on ${{ matrix.host }}"
        runs-on: ${{ matrix.runs-on }}
        timeout-minutes: 30
        needs: precheck
        if: >
            needs.precheck.outputs.HAS_NON_UI_CHANGES == '1' ||
            needs.precheck.outputs.IS_PUSH_TO_MASTER == '1'
        steps:
            - uses: actions/checkout@v3
            - uses: cachix/install-nix-action@v20
              with:
                  nix_path: nixpkgs=channel:nixos-22.05
            - uses: cachix/cachix-action@v12
              with:
                  name: fedibtc
                  authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

            - name: Clippy
              run: nix build -L .#ci.workspaceClippy

            - name: Test bridge
              timeout-minutes: 10
              if: matrix.run-tests
              run: |
                  nix build -L .#ci.${{ matrix.test-bridge }}

            - name: Test stability pool
              timeout-minutes: 10
              if: matrix.run-tests
              run: nix build -L .#ci.testStabilityPool

    build-linux:
        name: 'Build - linux'
        needs: precheck
        if: >
            needs.precheck.outputs.HAS_NON_UI_CHANGES == '1' ||
            needs.precheck.outputs.IS_PUSH_TO_MASTER == '1'
        runs-on: [self-hosted, linux]
        timeout-minutes: 60
        steps:
            - uses: actions/checkout@v3
            - uses: cachix/install-nix-action@v20
              with:
                  nix_path: nixpkgs=channel:nixos-22.05
            - uses: cachix/cachix-action@v12
              with:
                  name: fedibtc
                  authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

            - name: Build fedi-fedimint-pkgs
              run: nix build -L .#ci.fedi-fedimint-pkgs

            - name: Build fedi-fedimintd
              run: nix build -L .#ci.fedi-fedimintd

            - name: Build fedi-fedimint-cli
              run: nix build -L .#ci.fedi-fedimint-cli

            - name: Build fedi-wasm
              run: nix build -L .#wasm32-unknown.ci.fedi-wasm

            - name: Build gateway-pkgs
              run: nix build -L .#gateway-pkgs

            - name: Build gatewayd
              run: nix build -L .#gatewayd

            - name: Build gateway-cli
              run: nix build -L .#gateway-cli

            - name: Build devops-cli
              run: nix build -L .#ci.devops-cli


    build-android:
        name: 'Build - android'
        needs: precheck
        if: >
            needs.precheck.outputs.HAS_NON_UI_CHANGES == '1' ||
            needs.precheck.outputs.IS_PUSH_TO_MASTER == '1'
        runs-on: [self-hosted, linux]
        timeout-minutes: 60
        steps:
            - uses: actions/checkout@v3
            - uses: cachix/install-nix-action@v20
              with:
                  nix_path: nixpkgs=channel:nixos-22.05
            - uses: cachix/cachix-action@v12
              with:
                  name: fedibtc
                  authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

            - name: Build Android bridge artifacts
              run: nix develop --ignore-environment --command env HOME="$HOME" BUILD_ALL_BRIDGE_TARGETS=1 CARGO_PROFILE=ci scripts/ci/run-in-fs-dir-cache.sh build-bridge-android ./scripts/bridge/build-bridge-android.sh

    build-ios:
        name: 'Build - macos'
        needs: precheck
        if: >
            needs.precheck.outputs.HAS_NON_UI_CHANGES == '1' ||
            needs.precheck.outputs.IS_PUSH_TO_MASTER == '1'
        runs-on: [self-hosted, macos, arm64]
        timeout-minutes: 60
        steps:
            - uses: actions/checkout@v3
            - uses: cachix/install-nix-action@v20
              with:
                  nix_path: nixpkgs=channel:nixos-22.05
            - uses: cachix/cachix-action@v12
              with:
                  name: fedibtc
                  authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
              continue-on-error: true

            - name: Build iOS bridge artifacts
              # note: can't use --ignore-environment as it uses globally installed xcode
              run: nix develop .#xcode --command env HOME="$HOME" BUILD_ALL_BRIDGE_TARGETS=1 CARGO_PROFILE=ci scripts/ci/run-in-fs-dir-cache.sh build-bridge-ios ./scripts/bridge/build-bridge-ios.sh

    shell:
        strategy:
            matrix:
                host:
                    - linux
                    - macos-arm64
                include:
                    - on: linux
                      runs-on: [self-hosted, linux]
                      build-in-pr: true
                      timeout: 30
                      system: x86_64-linux
                    - host: macos-arm64
                      runs-on: [self-hosted, macos, arm64]
                      os: macOS
                      build-in-pr: true
                      timeout: 45
                      system: aarch64-darwin

        name: 'Dev shells - ${{ matrix.host }}'
        runs-on: ${{ matrix.runs-on }}
        timeout-minutes: ${{ matrix.timeout }}

        steps:
            - uses: actions/checkout@v3
              if: github.ref == 'refs/heads/master' || matrix.build-in-pr

            - uses: cachix/install-nix-action@v20
              if: github.ref == 'refs/heads/master' || matrix.build-in-pr
              with:
                  nix_path: nixpkgs=channel:nixos-22.05

            - uses: cachix/cachix-action@v12
              if: github.ref == 'refs/heads/master' || matrix.build-in-pr
              with:
                  name: fedibtc
                  authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
              continue-on-error: true

            - name: Dev shell
              if: (github.ref == 'refs/heads/master' || matrix.build-in-pr)
              run: nix build -L .#devShells.${{ matrix.system }}.default

    status:
      name: Status
      needs: [lint, build-workspace, build-linux, build-android, build-ios, shell]
      if: ${{ always() }}
      runs-on: ubuntu-latest
      steps:
        - name: Check status of all jobs
          if: >-
            ${{
              contains(needs.*.result, 'failure') ||
              contains(needs.*.result, 'cancelled')
            }}
          run: exit 1
