name: Publish APK to GitHub
on:
    workflow_dispatch:
    push:
        branches:
            - 'release/**.**'
            - '!release/**.**.**'
        paths:
            - 'bridge/**'
            - 'ui/native/**'
            - 'ui/common/**'
            - '!ui/native/ios/**' # Don't run for changes in /ios folder

jobs:
    release-android:
        name: Build Android APK and publish in GitHub draft release
        runs-on: buildjet-4vcpu-ubuntu-2204
        outputs:
            commit-to-deploy: ${{ steps.versioning.outputs.COMMIT_TO_DEPLOY }}
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2
              with:
                  submodules: true

            - uses: cachix/install-nix-action@v20
              with:
                  nix_path: nixpkgs=channel:nixos-22.05

            - uses: cachix/cachix-action@v12
              with:
                  name: fedibtc
                  authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

            - name: Build bridge
              run: nix develop .#cross --command just build-bridge-android

            - name: Build UI dependencies
              run: nix develop .#cross --command just build-ui-deps

            - name: Bump version & prep for APK build
              id: versioning
              run: |
                  git config --global user.email "dev@fedibtc.com"
                  git config --global user.name "Fedi Dev CI"
                  RELEASE_BRANCH_VERSION="${GITHUB_REF##*/}"
                  CURRENT_VERSION="$(npm pkg get version --ws false | sed 's/"//g')"
                  CURRENT_MINOR_VERSION="$(cut -d '.' -f 1,2 <<< "$CURRENT_VERSION")"
                  if [[ "$CURRENT_MINOR_VERSION" != "$RELEASE_BRANCH_VERSION" ]] && [[ "$RELEASE_BRANCH_VERSION" == *"."* ]];
                  then
                      echo 'Bumping npm minor version to $RELEASE_BRANCH_VERSION.0'
                      npm version --allow-same-version --force $RELEASE_BRANCH_VERSION.0
                  else
                      echo 'Bumping npm patch version'
                      npm version --allow-same-version --force patch
                  fi
                  echo "Bumping react-native version numbers to match npm"
                  npx react-native-version --target android
                  NEW_VERSION="$(npm pkg get version  --ws false | sed 's/"//g')"
                  echo "NEW_VERSION $NEW_VERSION"
                  echo "Pushing version commit to git branch"
                  git add package.json android/app/build.gradle && git commit -m "${NEW_VERSION}" && git push
                  echo "Saving new version + APK path as outputs for next steps in job"
                  echo "NEW_VERSION=$(npm pkg get version --ws false | sed 's/"//g')" >> $GITHUB_OUTPUT
                  echo "APK_PATH=android/app/build/outputs/apk/production/release/app-production-release-${NEW_VERSION}.apk" >> $GITHUB_OUTPUT
                  echo "Saving latest commit to output for 'call-deployment-workflow' job"
                  echo "COMMIT_TO_DEPLOY=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

            - name: Build APK
              run: |
                  cd android && bundle exec fastlane build_production_apk && cd ..

            - name: Rename APK with version
              run: |
                  RELEASE_PATH=./android/app/build/outputs/apk/production/release
                  SOURCE=$RELEASE_PATH/app-production-release.apk
                  DESTINATION=./${{ steps.versioning.outputs.APK_PATH }}
                  echo "Moving apk from $SOURCE to $DESTINATION"
                  mv $SOURCE $DESTINATION
                  echo "checking RELEASE_PATH $RELEASE_PATH"
                  ls $RELEASE_PATH

            - name: Create draft GitHub release with APK
              uses: softprops/action-gh-release@v1
              with:
                  tag_name: v${{ steps.versioning.outputs.NEW_VERSION }}
                  name: 'v${{ steps.versioning.outputs.NEW_VERSION }}'
                  body: 'This release was generated by CI with the latest APK for an upcoming release. Built from commit: ${{ steps.versioning.outputs.COMMIT_TO_DEPLOY }}'
                  draft: true
                  files: ./ui/native/${{ steps.versioning.outputs.APK_PATH }}

    call-deployment-workflow:
        name: Trigger deployment to Google Play for Internal Testing
        needs: release-android
        uses: ./.github/workflows/deploy-to-gp-internal-testing.yml
        secrets: inherit
        with:
            commit-to-deploy: ${{ needs.release-android.outputs.commit-to-deploy }}
