name: Publish APK to GitHub
on:
    workflow_dispatch:
    push:
        branches:
            - 'release/**.**'
            - '!release/**.**.**'
        paths:
            - 'bridge/**'
            - 'ui/native/**'
            - 'ui/common/**'
            - '!ui/native/ios/**' # Don't run for changes in /ios folder

jobs:
    release-android:
        name: Build Android APK and publish in GitHub draft release
        runs-on: buildjet-4vcpu-ubuntu-2204
        outputs:
            commit-to-deploy: ${{ steps.versioning.outputs.COMMIT_TO_DEPLOY }}
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2
              with:
                  submodules: true

            - uses: cachix/install-nix-action@v20
              with:
                  nix_path: nixpkgs=channel:nixos-22.05

            - uses: cachix/cachix-action@v12
              with:
                  name: fedibtc
                  authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

            - name: Build bridge
              run: nix develop .#cross --command just build-bridge-android

            - name: Build UI dependencies
              run: nix develop .#cross --command just build-ui-deps

            - name: Bump version & prep for APK build
              id: versioning
              run: nix develop .#cross --command just bump-version-native-ui

            - name: Build APK
              run: nix develop .#cross --command just build-production-apk

            - name: Rename APK with version
              run: |
                  RELEASE_PATH=./android/app/build/outputs/apk/production/release
                  SOURCE=$RELEASE_PATH/app-production-release.apk
                  DESTINATION=./${{ steps.versioning.outputs.APK_PATH }}
                  echo "Moving apk from $SOURCE to $DESTINATION"
                  mv $SOURCE $DESTINATION
                  echo "checking RELEASE_PATH $RELEASE_PATH"
                  ls $RELEASE_PATH

            - name: Create draft GitHub release with APK
              uses: softprops/action-gh-release@v1
              with:
                  tag_name: v${{ steps.versioning.outputs.NEW_VERSION }}
                  name: 'v${{ steps.versioning.outputs.NEW_VERSION }}'
                  body: 'This release was generated by CI with the latest APK for an upcoming release. Built from commit: ${{ steps.versioning.outputs.COMMIT_TO_DEPLOY }}'
                  draft: true
                  files: ./ui/native/${{ steps.versioning.outputs.APK_PATH }}

    call-deployment-workflow:
        name: Trigger deployment to Google Play for Internal Testing
        needs: release-android
        uses: ./.github/workflows/deploy-to-gp-internal-testing.yml
        secrets: inherit
        with:
            commit-to-deploy: ${{ needs.release-android.outputs.commit-to-deploy }}
