name: Test callable workflow
on:
    workflow_dispatch:
    workflow_call:
        inputs:
            commit-to-deploy:
                required: true
                type: string

jobs:
    build-publish-android-apk:
        name: Test callable workflow
        runs-on: buildjet-4vcpu-ubuntu-2204
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2
              with:
                  submodules: true
                  ref: ${{ inputs.commit-to-deploy }}

            - name: Test
              run: |
                  git config --global user.name "Fedi Dev CI"
                  RELEASE_BRANCH_VERSION="${GITHUB_REF##*/}"
                  CURRENT_VERSION="$(npm pkg get version | sed 's/"//g')"
                  CURRENT_MINOR_VERSION="$(cut -d '.' -f 1,2 <<< "$CURRENT_VERSION")"
                  git log -1
                  echo "test"
                  echo "$GITHUB_REF"
                  echo "$RELEASE_BRANCH_VERSION"
                  echo "$CURRENT_VERSION"
                  echo "$CURRENT_MINOR_VERSION"
